import type { Exam } from "./types";

export const electricsExam: Exam = {
  id: "electrics",
  title: "Basic Electrics",
  subtitle: "Electrical principles and fundamentals — Ohm's law, AC/DC, power, conductors, protection theory",
  description: "A fundamentals-focused exam covering electrical principles that underpin the regulatory and testing exams: Ohm's law and power, DC/AC circuit behaviour, three-phase basics, cable/conductor properties, protective device characteristics, earthing-system theory, and electric-shock physiology. Designed for L2/L3 trainees and as a refresher before the 18th Edition or AM2.",
  format: "Each attempt = 40 multiple-choice questions across 5 sections. Pass at 70%+. The bank rotates through 5 distinct variants per section so retries draw fresh material.",
  passPercent: 0.7,
  sections: [
    {
      id: "section-1",
      title: "Section 1 — Ohm's Law & Power",
      variants: [
        {
          id: "v1",
          questions: [
            { number: 1, prompt: "A 12 V DC supply drives a current of 0.4 A through a load. The load resistance is:", options: { A: "4.8 Ω", B: "0.033 Ω", C: "300 Ω", D: "30 Ω" }, answer: "D", explanation: "R = V / I = 12 / 0.4 = 30 Ω. Distractor 4.8 is V × I (power, not resistance); 0.033 is the inverse (I/V); 300 is a decimal slip." },
            { number: 2, prompt: "A heater dissipates 2.3 kW from a 230 V supply. The current drawn is approximately:", options: { A: "10 A", B: "1 A", C: "0.1 A", D: "100 A" }, answer: "A", explanation: "I = P / V = 2300 / 230 = 10 A. The heater rating in kW divided by the voltage in V (with both expressed consistently) gives a quick sanity check." },
            { number: 3, prompt: "Two resistors, 6 Ω and 12 Ω, are connected in parallel. The combined resistance is:", options: { A: "4 Ω", B: "9 Ω", C: "18 Ω", D: "2 Ω" }, answer: "A", explanation: "1/R = 1/6 + 1/12 = 2/12 + 1/12 = 3/12, so R = 4 Ω. For two resistors in parallel R = (R1 × R2) / (R1 + R2) = 72/18 = 4 Ω." },
            { number: 4, prompt: "Three 30 Ω elements are connected in series across a 230 V supply. The current drawn is:", options: { A: "2.56 A", B: "7.67 A", C: "23 A", D: "0.39 A" }, answer: "A", explanation: "Series resistance = 30 + 30 + 30 = 90 Ω. I = V/R = 230/90 ≈ 2.56 A. The 7.67 A value would be the current through one element on its own across 230 V." },
            { number: 5, prompt: "A 3 kW immersion heater operates for 45 minutes. The energy consumed is:", options: { A: "2.25 kWh", B: "1.35 kWh", C: "135 kWh", D: "8.1 MJ" }, answer: "A", explanation: "E = P × t = 3 kW × 0.75 h = 2.25 kWh. The 1.35 kWh figure (B) corresponds to 27 minutes; 8.1 MJ is the same energy expressed in joules (2.25 × 3600 = 8100 kJ = 8.1 MJ), but the question asked in kWh." },
            { number: 6, prompt: "A potential divider has 10 V across it. R1 (top) = 4 kΩ, R2 (bottom) = 6 kΩ. The voltage across R2 is:", options: { A: "4 V", B: "1.67 V", C: "10 V", D: "6 V" }, answer: "D", explanation: "V_R2 = V × R2 / (R1 + R2) = 10 × 6 / 10 = 6 V. The 4 V option is across R1, the common error of swapping the numerator." },
            { number: 7, prompt: "An electric motor takes 8 A from a 230 V supply with an input power of 1.6 kW. The efficiency, given a mechanical output of 1.4 kW, is:", options: { A: "87.5%", B: "80%", C: "70%", D: "95%" }, answer: "A", explanation: "η = P_out / P_in × 100 = 1400 / 1600 × 100 = 87.5%. The 80% figure (B) would correspond to 1.28 kW out, and the 70% figure to 1.12 kW out — both common rounded distractors." },
            { number: 8, prompt: "A resistive load draws 12 A on 230 V. Recalculated using P = I²R, the load's power dissipation is:", options: { A: "2760 W", B: "1656 W", C: "166 W", D: "27.6 kW" }, answer: "A", explanation: "Either P = VI = 230 × 12 = 2760 W, or first find R = V/I = 19.17 Ω then P = I²R = 144 × 19.17 ≈ 2760 W. The 1656 W answer (B) reflects an incorrect 144 × 11.5 calculation." }
          ]
        },
        {
          id: "v2",
          questions: [
            { number: 1, prompt: "A 240 V supply feeds a load of resistance 48 Ω. The current drawn is:", options: { A: "5 A", B: "0.2 A", C: "11.5 A", D: "200 mA" }, answer: "A", explanation: "I = V / R = 240 / 48 = 5 A. Distractor 0.2 A reflects swapping numerator and denominator; 11.5 A is V/I rather than V/R for I; 200 mA = 0.2 A under a different unit." },
            { number: 2, prompt: "Three 6 Ω resistors are connected in parallel. The total resistance is:", options: { A: "18 Ω", B: "6 Ω", C: "3 Ω", D: "2 Ω" }, answer: "D", explanation: "Identical resistors in parallel: R_total = R / n = 6 / 3 = 2 Ω. Series would have given 18 Ω; treating as two-in-parallel only would give 3 Ω." },
            { number: 3, prompt: "A 100 W lamp at 230 V has an operating resistance of approximately:", options: { A: "2.3 Ω", B: "23 Ω", C: "529 Ω", D: "23 kΩ" }, answer: "C", explanation: "R = V² / P = 230² / 100 = 52900 / 100 = 529 Ω. This is the hot-filament resistance; cold filament would be ~10× lower, contributing to the inrush current at switch-on." },
            { number: 4, prompt: "A 4 Ω resistor and a 12 Ω resistor are connected in series across 32 V. The current is:", options: { A: "2 A", B: "8 A", C: "4 A", D: "0.25 A" }, answer: "A", explanation: "R_total = 4 + 12 = 16 Ω. I = V / R = 32 / 16 = 2 A. The 8 A figure would arise from using only one of the resistors; 0.25 A is R/V rather than V/R." },
            { number: 5, prompt: "A 2 kW kettle is rated 230 V. The cold (steady-state) element resistance is approximately:", options: { A: "8.7 Ω", B: "115 Ω", C: "26.5 Ω", D: "230 Ω" }, answer: "C", explanation: "R = V² / P = 230² / 2000 = 52900 / 2000 = 26.45 Ω. The 8.7 Ω figure would have come from V/P rather than V²/P." },
            { number: 6, prompt: "Two resistors, 8 Ω and 24 Ω, are in parallel. The pair is then placed in series with a 4 Ω resistor across a 20 V supply. The supply current is:", options: { A: "1 A", B: "5 A", C: "2.5 A", D: "2 A" }, answer: "D", explanation: "Parallel pair: (8 × 24)/(8 + 24) = 192/32 = 6 Ω. Total = 6 + 4 = 10 Ω. I = 20/10 = 2 A. Common error: adding 8 + 24 + 4 = 36 Ω (treating all three in series) gives 0.56 A which isn't on the list." },
            { number: 7, prompt: "A heating element of resistance 23 Ω is energised on 230 V. The power dissipated is:", options: { A: "100 W", B: "1 kW", C: "5.3 kW", D: "2.3 kW" }, answer: "D", explanation: "P = V² / R = 230² / 23 = 52900 / 23 = 2300 W = 2.3 kW. The 1 kW distractor would arise from the wrong squaring (230 instead of 230²)." },
            { number: 8, prompt: "A motor circuit shows a starting current of 60 A on a 230 V single-phase supply. The instantaneous (apparent) power demand is closest to:", options: { A: "0.27 kVA", B: "138 kVA", C: "0.38 kVA", D: "13.8 kVA" }, answer: "D", explanation: "S = V × I = 230 × 60 = 13800 VA = 13.8 kVA. Note this is apparent power and ignores power factor; true power would be lower (P = S × cos φ)." }
          ]
        },
        {
          id: "v3",
          questions: [
            { number: 1, prompt: "A 4.7 kΩ resistor has 9 V across it. The current through it is approximately:", options: { A: "1.9 mA", B: "9 mA", C: "19 mA", D: "0.19 mA" }, answer: "A", explanation: "I = V/R = 9 / 4700 ≈ 0.00191 A = 1.91 mA. Working in volts and ohms keeps the answer in amperes; converting to milliamperes by ×1000 gives 1.9 mA." },
            { number: 2, prompt: "Two 100 Ω resistors in parallel are connected in series with a third 100 Ω resistor. The total resistance is:", options: { A: "300 Ω", B: "150 Ω", C: "200 Ω", D: "67 Ω" }, answer: "B", explanation: "Two 100 Ω in parallel = 50 Ω. In series with a 100 Ω: 50 + 100 = 150 Ω. The 67 Ω figure (D) would be all three in parallel." },
            { number: 3, prompt: "A circuit dissipates 720 W when 6 A flows. The resistance of the load is:", options: { A: "4.32 kΩ", B: "120 Ω", C: "20 Ω", D: "0.05 Ω" }, answer: "C", explanation: "P = I²R, so R = P/I² = 720 / 36 = 20 Ω. The 120 Ω figure would arise from R = P/I (wrong formula)." },
            { number: 4, prompt: "A length of conductor with resistance 0.5 Ω carries 25 A. The power lost as heat in the conductor is:", options: { A: "12.5 W", B: "312.5 W", C: "62.5 W", D: "625 W" }, answer: "B", explanation: "P = I² R = 625 × 0.5 = 312.5 W. The I² term highlights why doubling the current quadruples the cable losses — a key point in voltage-drop and cable-sizing decisions." },
            { number: 5, prompt: "A 6 V battery with negligible internal resistance feeds a 200 Ω load and a 600 Ω load in parallel. The total current drawn is:", options: { A: "10 mA", B: "40 mA", C: "30 mA", D: "75 mA" }, answer: "B", explanation: "Each branch acts independently across the battery. I_200 = 6/200 = 30 mA; I_600 = 6/600 = 10 mA; total = 40 mA. KCL at the supply node: branch currents sum to the supply current." },
            { number: 6, prompt: "A 12 V battery has an internal resistance of 0.6 Ω and feeds a 5.4 Ω external load. The terminal voltage on load is:", options: { A: "12 V", B: "1.2 V", C: "9.6 V", D: "10.8 V" }, answer: "D", explanation: "I = 12 / (0.6 + 5.4) = 12/6 = 2 A. Volt drop across internal r = 2 × 0.6 = 1.2 V. Terminal voltage = 12 − 1.2 = 10.8 V. The full EMF only appears at no-load." },
            { number: 7, prompt: "An immersion heater dissipates 3 kW at 230 V. If the supply voltage drops to 207 V (a 10% sag), the new power dissipation is approximately:", options: { A: "2.43 kW", B: "2.7 kW", C: "3 kW", D: "3.3 kW" }, answer: "A", explanation: "Resistance is roughly fixed; P ∝ V². New P = 3 × (207/230)² = 3 × 0.81 = 2.43 kW. A 10% voltage drop causes a 19% power drop — a frequent reason heaters under-perform on long, undersized supplies." },
            { number: 8, prompt: "Three lamps rated 100 W, 60 W and 40 W (all at 230 V) are run in parallel from a 230 V supply for 5 hours. The total energy used is:", options: { A: "200 Wh", B: "1.0 kWh", C: "10 kWh", D: "100 Wh" }, answer: "B", explanation: "Total power = 100 + 60 + 40 = 200 W. Energy = 200 W × 5 h = 1000 Wh = 1 kWh. Since the lamps are in parallel and all rated at the same supply voltage, their wattages simply add. (1000 Wh = 1.0 kWh; option A's 200 Wh is the power, not the energy)." }
          ]
        },
        {
          id: "v4",
          questions: [
            { number: 1, prompt: "A 9 kW electric shower at 230 V draws a steady-state current of approximately:", options: { A: "9 A", B: "21 A", C: "39 A", D: "55 A" }, answer: "C", explanation: "I = P/V = 9000/230 = 39.1 A. Showers in this rating range push 10 mm² T+E into use because the design current sits comfortably above 32 A." },
            { number: 2, prompt: "Doubling the resistance and halving the voltage of a circuit, the current changes by a factor of:", options: { A: "0.25", B: "0.5", C: "1", D: "2" }, answer: "A", explanation: "I = V/R. New I = (V/2) / (2R) = V / 4R = original I / 4. The current falls to a quarter of the original — frequently overlooked because each change separately gives ½ but they multiply, not cancel." },
            { number: 3, prompt: "The conductance of a 50 Ω resistor is:", options: { A: "0.02 S", B: "20 S", C: "0.5 S", D: "50 S" }, answer: "A", explanation: "G = 1/R = 1/50 = 0.02 S (siemens). Conductance is the reciprocal of resistance; for two conductors in parallel, conductances add directly." },
            { number: 4, prompt: "A series-parallel network has a 10 Ω resistor in series with a parallel combination of 4 Ω and 12 Ω. The total resistance is:", options: { A: "13 Ω", B: "16 Ω", C: "26 Ω", D: "10.27 Ω" }, answer: "A", explanation: "Parallel pair: (4 × 12)/(4 + 12) = 48/16 = 3 Ω. In series with 10 Ω: 10 + 3 = 13 Ω. The 16 Ω option treats the parallel pair as a 6 Ω series combination by mistake." },
            { number: 5, prompt: "A 1500 W water heater is supplied at 230 V. The resistance of its element (assumed constant) is:", options: { A: "10.4 Ω", B: "15.3 Ω", C: "35.3 Ω", D: "152 Ω" }, answer: "C", explanation: "R = V²/P = 230²/1500 = 52900/1500 = 35.3 Ω. The 15.3 Ω figure would have come from V/P (wrong formula)." },
            { number: 6, prompt: "Through a 4 Ω resistor, the current is 3 A. The voltage developed across the resistor is:", options: { A: "0.75 V", B: "1.33 V", C: "7 V", D: "12 V" }, answer: "D", explanation: "V = IR = 3 × 4 = 12 V. The 0.75 V option is I/R rather than IR; the 1.33 V option is R/I. Dimensional sanity: amps × ohms = volts." },
            { number: 7, prompt: "An LED draws 20 mA at a forward voltage of 2 V from a 12 V source. The series limiting resistor required is:", options: { A: "100 Ω", B: "400 Ω", C: "500 Ω", D: "600 Ω" }, answer: "C", explanation: "Volt drop across the resistor = 12 − 2 = 10 V. R = V/I = 10/0.02 = 500 Ω. Common error: dividing by 12 V (the supply, not the resistor drop) gives 600 Ω." },
            { number: 8, prompt: "A 230 V motor is rated 1.1 kW with an efficiency of 80%. The current drawn from the supply (at unity power factor) is approximately:", options: { A: "3.8 A", B: "4.8 A", C: "6 A", D: "9.6 A" }, answer: "C", explanation: "P_in = P_out / η = 1100 / 0.8 = 1375 W. I = P_in / V = 1375 / 230 = 5.98 A ≈ 6 A. Forgetting efficiency gives 4.78 A; treating efficiency as a multiplier rather than a divisor gives 3.83 A." }
          ]
        },
        {
          id: "v5",
          questions: [
            { number: 1, prompt: "A current of 50 mA flows through a 240 Ω resistor. The power dissipated is:", options: { A: "0.6 W", B: "6 W", C: "12 W", D: "60 W" }, answer: "A", explanation: "P = I²R = (0.05)² × 240 = 0.0025 × 240 = 0.6 W. Working in amperes (0.05 A, not 50) avoids the common factor-of-1000 slip." },
            { number: 2, prompt: "A circuit shows a steady current draw of 1.5 A on 24 V. Switching to 12 V (with the same load resistance) the current becomes:", options: { A: "0.75 A", B: "0.375 A", C: "1.5 A", D: "3 A" }, answer: "A", explanation: "Resistance is fixed at R = 24/1.5 = 16 Ω. New I = 12/16 = 0.75 A. Halving the voltage halves the current for a fixed resistance — direct proportionality." },
            { number: 3, prompt: "Three resistors, 2 Ω, 3 Ω, 6 Ω, are connected in parallel. The total resistance is:", options: { A: "11 Ω", B: "6 Ω", C: "3 Ω", D: "1 Ω" }, answer: "D", explanation: "1/R = 1/2 + 1/3 + 1/6 = 3/6 + 2/6 + 1/6 = 6/6 = 1, so R = 1 Ω. A handy mental check: total parallel resistance is always less than the smallest branch resistor (2 Ω here)." },
            { number: 4, prompt: "A 230 V supply feeds two heaters: 2 kW and 3 kW, both used together. The total current drawn is:", options: { A: "21.7 A", B: "13 A", C: "26 A", D: "5 A" }, answer: "A", explanation: "Total power = 5 kW. I = P/V = 5000/230 = 21.7 A. The 13 A figure treats only the 3 kW heater; 26 A would treat 6 kW total." },
            { number: 5, prompt: "A wirewound resistor is marked 5 W, 100 Ω. The maximum safe current through it is:", options: { A: "0.05 A", B: "0.5 A", C: "0.224 A", D: "2.24 A" }, answer: "C", explanation: "P_max = I²R, so I_max = √(P/R) = √(5/100) = √0.05 ≈ 0.224 A. Exceeding this raises the resistor temperature and risks burnout. The 0.5 A figure ignores the square root." },
            { number: 6, prompt: "An ammeter in series with a 40 Ω lamp reads 5.5 A. The voltage across the lamp is:", options: { A: "0.14 V", B: "7.27 V", C: "220 V", D: "230 V" }, answer: "C", explanation: "V = IR = 5.5 × 40 = 220 V. The 7.27 V figure is V/R rather than IR; the 230 V option is the headline supply but not necessarily the lamp's terminal voltage if there is appreciable cable resistance." },
            { number: 7, prompt: "A bell circuit has a transformer with a 230 V primary and a 12 V secondary. Primary current is 50 mA. Assuming 100% efficiency, the secondary current is:", options: { A: "50 mA", B: "19.2 A", C: "9.6 A", D: "0.96 A" }, answer: "D", explanation: "P_in = P_out → V_p × I_p = V_s × I_s. I_s = (230 × 0.05) / 12 = 11.5 / 12 = 0.958 A ≈ 0.96 A. The current ratio is the inverse of the voltage ratio (the turns ratio)." },
            { number: 8, prompt: "A 1.6 kW load runs for 4 hours daily. Assuming a tariff of 30p per kWh, the weekly running cost is approximately:", options: { A: "£1.34", B: "£3.20", C: "£13.44", D: "£44.80" }, answer: "C", explanation: "Daily energy = 1.6 × 4 = 6.4 kWh. Weekly = 6.4 × 7 = 44.8 kWh. Cost = 44.8 × 0.30 = £13.44. Multi-step problems like this come up in domestic energy assessments and tariff calculations." }
          ]
        }
      ]
    },
    {
      id: "section-2",
      title: "Section 2 — AC Theory & Three-Phase",
      variants: [
        {
          id: "v1",
          questions: [
            { number: 1, prompt: "The peak value of the UK 230 V_rms single-phase supply waveform is approximately:", options: { A: "163 V", B: "230 V", C: "325 V", D: "400 V" }, answer: "C", explanation: "V_peak = V_rms × √2 = 230 × 1.414 ≈ 325 V. The 163 V figure is V_rms / √2 (mistakenly applied the inverse). Insulation must withstand at least the peak voltage, not just the RMS value." },
            { number: 2, prompt: "A 50 Hz sinewave has a period of:", options: { A: "0.005 s", B: "0.2 s", C: "0.05 s", D: "0.02 s" }, answer: "D", explanation: "T = 1/f = 1/50 = 0.02 s = 20 ms. Each mains cycle takes 20 ms; the half-cycle (zero-crossing to zero-crossing through one polarity) takes 10 ms — relevant when interpreting RCD and breaker trip times." },
            { number: 3, prompt: "An inductor of 0.05 H is connected to a 50 Hz supply. Its inductive reactance X_L is approximately:", options: { A: "15.7 Ω", B: "3.14 Ω", C: "31.4 Ω", D: "157 Ω" }, answer: "A", explanation: "X_L = 2πfL = 2π × 50 × 0.05 = π × 5 = 15.71 Ω. The 31.4 Ω figure (C) drops a factor of 2; 3.14 Ω simply forgets the f and L scaling." },
            { number: 4, prompt: "A capacitor of 100 µF is connected to a 50 Hz supply. Its capacitive reactance X_C is approximately:", options: { A: "31.8 Ω", B: "318 Ω", C: "3.18 Ω", D: "318 mΩ" }, answer: "A", explanation: "X_C = 1 / (2πfC) = 1 / (2π × 50 × 100 × 10⁻⁶) = 1 / 0.0314 = 31.8 Ω. The 318 Ω figure misplaces the µF unit by a decade." },
            { number: 5, prompt: "A series RL circuit has R = 30 Ω and X_L = 40 Ω. The impedance Z is:", options: { A: "10 Ω", B: "35 Ω", C: "50 Ω", D: "70 Ω" }, answer: "C", explanation: "Z = √(R² + X²) = √(900 + 1600) = √2500 = 50 Ω. The 70 Ω figure (D) is the algebraic sum (R + X), invalid because R and X are 90° apart." },
            { number: 6, prompt: "A 230 V single-phase load draws 8 A at 0.8 power factor lagging. The true power is:", options: { A: "230 W", B: "2300 W", C: "1840 W", D: "1472 W" }, answer: "D", explanation: "P = V × I × cos φ = 230 × 8 × 0.8 = 1472 W. The 1840 VA figure (C) is the apparent power S; reactive power Q = 230 × 8 × 0.6 = 1104 VAr." },
            { number: 7, prompt: "A 400 V three-phase star-connected (Y) supply has a phase-to-neutral voltage of:", options: { A: "115 V", B: "692 V", C: "400 V", D: "230 V" }, answer: "D", explanation: "In star, V_L = √3 × V_ph, so V_ph = V_L / √3 = 400 / 1.732 ≈ 230 V. The UK distribution standard 400/230 V is precisely this relationship." },
            { number: 8, prompt: "In a balanced three-phase delta system, the relationship between line current I_L and phase current I_ph is:", options: { A: "I_L = I_ph", B: "I_L = 3 × I_ph", C: "I_L = I_ph / √3", D: "I_L = √3 × I_ph" }, answer: "D", explanation: "Delta: line voltage equals phase voltage (V_L = V_ph) but line current is √3 × phase current (I_L = √3 × I_ph). Star is the converse: V_L = √3 × V_ph and I_L = I_ph." }
          ]
        },
        {
          id: "v2",
          questions: [
            { number: 1, prompt: "The peak-to-peak voltage of a 230 V_rms sinewave is approximately:", options: { A: "230 V", B: "325 V", C: "460 V", D: "650 V" }, answer: "D", explanation: "V_peak ≈ 325 V; peak-to-peak = 2 × V_peak ≈ 650 V. The peak-to-peak swing matters for oscilloscope work and for selecting capacitor working-voltage ratings." },
            { number: 2, prompt: "An RC series circuit has R = 60 Ω and X_C = 80 Ω. The impedance Z is:", options: { A: "20 Ω", B: "80 Ω", C: "100 Ω", D: "140 Ω" }, answer: "C", explanation: "Z = √(R² + X²) = √(3600 + 6400) = √10000 = 100 Ω. Same Pythagorean form as RL — only the phase-angle sign changes (current leads voltage in capacitive circuits)." },
            { number: 3, prompt: "A 230 V load draws 12 A at 0.7 lagging power factor. The reactive power Q is approximately:", options: { A: "1.97 kVAr", B: "1.93 kVAr", C: "2.34 kVAr", D: "2.76 kVAr" }, answer: "A", explanation: "S = V × I = 230 × 12 = 2760 VA. sin φ = √(1 − 0.7²) = √0.51 ≈ 0.714. Q = S × sin φ = 2760 × 0.714 ≈ 1971 VAr ≈ 1.97 kVAr. Don't confuse Q with the true power P = 2760 × 0.7 = 1932 W." },
            { number: 4, prompt: "A balanced three-phase 400/230 V supply feeds a delta-connected load. The line voltage and phase voltage of the load are:", options: { A: "400 V and 230 V", B: "230 V and 400 V", C: "230 V and 230 V", D: "400 V and 400 V" }, answer: "D", explanation: "In delta, V_L = V_ph, so each phase winding sees the full 400 V line voltage. In a star (Y) load on the same supply, each winding would see 230 V_ph." },
            { number: 5, prompt: "A 50 Hz purely inductive load has L = 0.1 H. Its reactance is:", options: { A: "3.14 Ω", B: "100 Ω", C: "62.8 Ω", D: "31.4 Ω" }, answer: "D", explanation: "X_L = 2πfL = 2π × 50 × 0.1 = 10π ≈ 31.4 Ω. The 62.8 Ω figure (C) drops a factor of 2 in the formula." },
            { number: 6, prompt: "Phase rotation in UK three-phase systems is conventionally L1 → L2 → L3, with cable colours:", options: { A: "Brown — black — grey", B: "Red — yellow — blue", C: "Black — red — yellow", D: "Brown — blue — black" }, answer: "A", explanation: "Since the harmonised colour change (April 2006), three-phase line conductors are brown (L1), black (L2), grey (L3). The old red/yellow/blue scheme is still seen on legacy installations but is no longer compliant for new work." },
            { number: 7, prompt: "A balanced three-phase star-connected 400 V load draws a line current of 25 A at unity power factor. The total true power is:", options: { A: "10 kW", B: "5.75 kW", C: "17.3 kW", D: "29.0 kW" }, answer: "C", explanation: "P = √3 × V_L × I_L × cos φ = 1.732 × 400 × 25 × 1 ≈ 17320 W = 17.3 kW. Forgetting the √3 factor (treating 400 × 25 as the answer) gives 10 kW; using 3 instead of √3 gives 30 kW." },
            { number: 8, prompt: "Power factor correction by adding a capacitor in parallel with an inductive load:", options: { A: "Increases the true power but leaves the apparent power unchanged", B: "Reduces both true and reactive power equally", C: "Increases the supply voltage at the load terminals", D: "Reduces the line current and brings the power factor closer to unity, with no change in true power" }, answer: "D", explanation: "PF correction supplies the reactive power locally, cancelling some of the inductive reactive demand. The line current falls (less I × Z volt drop, lower I²R losses), the true power consumed by the load is unchanged, and the apparent power drawn from the supply falls." }
          ]
        },
        {
          id: "v3",
          questions: [
            { number: 1, prompt: "The instantaneous voltage v(t) = 325 sin(2π × 50 × t) describes a UK mains waveform. Its RMS value is:", options: { A: "163 V", B: "207 V", C: "230 V", D: "325 V" }, answer: "C", explanation: "V_rms = V_peak / √2 = 325 / 1.414 ≈ 230 V. The 163 V figure (A) divides peak by 2 instead of √2, a frequent slip." },
            { number: 2, prompt: "A capacitor offers high reactance at low frequencies and low reactance at high frequencies. Compared to 50 Hz, at 200 Hz the reactance of a 50 µF capacitor is:", options: { A: "Four times higher", B: "Twice as high", C: "Half as high", D: "A quarter as high" }, answer: "D", explanation: "X_C = 1/(2πfC); X_C is inversely proportional to f, so quadrupling f quarters X_C. The 200 Hz value is a quarter of the 50 Hz value." },
            { number: 3, prompt: "An RLC series circuit has R = 50 Ω, X_L = 120 Ω, X_C = 80 Ω. Net reactance X = X_L − X_C, and impedance Z is:", options: { A: "64 Ω", B: "50 Ω", C: "40 Ω", D: "150 Ω" }, answer: "A", explanation: "Net X = 120 − 80 = 40 Ω. Z = √(R² + X²) = √(2500 + 1600) = √4100 ≈ 64 Ω. The 50 Ω option (B) ignores the reactance entirely; 150 Ω adds R + X linearly." },
            { number: 4, prompt: "A balanced three-phase load draws 20 A line current at 400 V line voltage and a true power of 11 kW. The power factor is approximately:", options: { A: "0.6", B: "0.69", C: "1.0", D: "0.79" }, answer: "D", explanation: "S = √3 × V_L × I_L = 1.732 × 400 × 20 = 13860 VA ≈ 13.86 kVA. cos φ = P/S = 11/13.86 ≈ 0.79. The 0.69 figure would have come from using 16 kVA (skipping the √3 factor)." },
            { number: 5, prompt: "Reactive power is measured in:", options: { A: "Watts (W)", B: "Volt-amperes (VA)", C: "Volt-amperes reactive (VAr)", D: "Joules (J)" }, answer: "C", explanation: "True power P is in W, apparent power S is in VA, reactive power Q is in VAr. The same numerical values arise from V × I but they describe different aspects of an AC circuit's energy flow." },
            { number: 6, prompt: "On a UK 400 V three-phase TN system, the line-to-neutral voltage is closest to:", options: { A: "230 V", B: "115 V", C: "240 V", D: "400 V" }, answer: "A", explanation: "Star configuration: V_L = √3 × V_ph, so V_ph = 400 / √3 ≈ 230 V. This is the headline UK single-phase domestic voltage, derived from the secondary star point of the local distribution transformer." },
            { number: 7, prompt: "An inductive load takes 5 kW true power at 0.6 lagging power factor on a single-phase 230 V supply. The supply current is:", options: { A: "36 A", B: "21.7 A", C: "13 A", D: "50 A" }, answer: "A", explanation: "I = P / (V × cos φ) = 5000 / (230 × 0.6) = 5000 / 138 ≈ 36.2 A. The 21.7 A figure assumes unity power factor; correcting the PF would reduce the current toward 21.7 A." },
            { number: 8, prompt: "In a balanced three-phase 4-wire star system, the neutral current is:", options: { A: "Zero (balanced loads)", B: "√3 times the line current", C: "Equal to the line current", D: "Always 32 A by convention" }, answer: "A", explanation: "When the three line currents are equal in magnitude and 120° apart, they sum to zero at the star point — neutral current is zero. Imbalance and harmonic distortion (especially triplen harmonics) put real current back into the neutral." }
          ]
        },
        {
          id: "v4",
          questions: [
            { number: 1, prompt: "The form factor of a sinusoidal waveform (RMS / mean rectified) is:", options: { A: "0.707", B: "1.732", C: "1.414", D: "1.11" }, answer: "D", explanation: "For a sine: V_rms = 0.707 × V_peak; mean rectified = 0.637 × V_peak; form factor = 0.707 / 0.637 ≈ 1.11. The 1.414 figure is √2 (the peak factor), 1.732 is √3 (three-phase factor)." },
            { number: 2, prompt: "A 100 µF capacitor in series with a 200 Ω resistor at 50 Hz has an impedance of approximately:", options: { A: "202.5 Ω", B: "200 Ω", C: "31.8 Ω", D: "232 Ω" }, answer: "A", explanation: "X_C = 1/(2π × 50 × 100 × 10⁻⁶) = 31.8 Ω. Z = √(200² + 31.8²) = √(40000 + 1011) = √41011 ≈ 202.5 Ω. The 232 Ω figure is the linear sum (200 + 31.8), wrong because R and X are 90° apart." },
            { number: 3, prompt: "Three identical resistive loads connected in star draw 10 A line current from a 400 V supply. The total power dissipated is:", options: { A: "6.93 kW", B: "4 kW", C: "2.3 kW", D: "12 kW" }, answer: "A", explanation: "Resistive load: cos φ = 1. P = √3 × V_L × I_L = 1.732 × 400 × 10 = 6928 W ≈ 6.93 kW. Each phase contributes 2.31 kW (V_ph × I_ph at 230 V × 10 A); three phases sum to 6.93 kW." },
            { number: 4, prompt: "A 50 Hz, 230 V single-phase circuit has a load with R = 24 Ω and X_L = 32 Ω. The current drawn is:", options: { A: "4.6 A", B: "9.6 A", C: "7.2 A", D: "5.75 A" }, answer: "D", explanation: "Z = √(24² + 32²) = √(576 + 1024) = √1600 = 40 Ω. I = V/Z = 230/40 = 5.75 A. Treating only R gives 9.58 A (wrong); using only X_L gives 7.19 A (also wrong)." },
            { number: 5, prompt: "The frequency of the UK supply is normally maintained within tight limits around:", options: { A: "50 Hz", B: "60 Hz", C: "100 Hz", D: "400 Hz" }, answer: "A", explanation: "UK and most of Europe: 50 Hz. North America operates at 60 Hz. 400 Hz is found in aircraft and some military supplies because higher frequency permits smaller, lighter transformers." },
            { number: 6, prompt: "The angle between voltage and current in a purely capacitive AC circuit is:", options: { A: "Voltage leads current by 90°", B: "180° (anti-phase)", C: "0° (in phase)", D: "Current leads voltage by 90°" }, answer: "D", explanation: "ICE — in a Capacitor, current leads voltage. ELI — in an inductor, EMF leads current. Mnemonic: ELI the ICE-man." },
            { number: 7, prompt: "A delta-connected 400 V three-phase motor takes a phase current of 14 A. The line current is approximately:", options: { A: "8.1 A", B: "14 A", C: "24.2 A", D: "42 A" }, answer: "C", explanation: "Delta: I_L = √3 × I_ph = 1.732 × 14 ≈ 24.2 A. The 14 A figure (B) is correct only for star (where I_L = I_ph)." },
            { number: 8, prompt: "An induction motor is fed at 400 V three-phase, drawing 18 A line current at 0.85 lagging power factor. The input true power is approximately:", options: { A: "6.1 kW", B: "14.7 kW", C: "12.5 kW", D: "10.6 kW" }, answer: "D", explanation: "P = √3 × V_L × I_L × cos φ = 1.732 × 400 × 18 × 0.85 ≈ 10599 W ≈ 10.6 kW. The 12.5 kW figure forgets the power factor; 6.1 kW skips the √3." }
          ]
        },
        {
          id: "v5",
          questions: [
            { number: 1, prompt: "Why is the RMS (effective) value of an AC waveform used in power calculations?", options: { A: "It equals the average over one cycle", B: "It is the peak value times π", C: "It is the peak value divided by 2", D: "It equals the DC current that produces the same heating effect in a resistor" }, answer: "D", explanation: "RMS is defined so that an AC current of I_rms produces the same I²R heating in a pure resistance as a DC current of I. For sine: I_rms = I_peak / √2. The arithmetic mean of a full sine cycle is zero." },
            { number: 2, prompt: "A 230 V single-phase supply feeds a load with apparent power 4 kVA at 0.8 lagging PF. The true and reactive powers are:", options: { A: "P = 4 kW, Q = 0", B: "P = 5 kW, Q = 4 kVAr", C: "P = 2.4 kW, Q = 3.2 kVAr", D: "P = 3.2 kW, Q = 2.4 kVAr" }, answer: "D", explanation: "P = S × cos φ = 4 × 0.8 = 3.2 kW. Q = S × sin φ = 4 × 0.6 = 2.4 kVAr (sin of arccos 0.8 is 0.6). Power triangle: S² = P² + Q²: 16 = 10.24 + 5.76 = 16. Check." },
            { number: 3, prompt: "A 25 µF capacitor across a 230 V, 50 Hz supply draws a current of approximately:", options: { A: "0.18 A", B: "0.018 A", C: "18.1 A", D: "1.81 A" }, answer: "D", explanation: "X_C = 1/(2π × 50 × 25 × 10⁻⁶) = 1/0.00785 ≈ 127.3 Ω. I = V/X_C = 230/127.3 ≈ 1.81 A. The 0.18 A option (A) is a decade slip on the µF unit." },
            { number: 4, prompt: "A three-phase induction motor is rated 7.5 kW at 400 V, 0.8 PF, with efficiency 90%. The line current drawn is approximately:", options: { A: "10.8 A", B: "13.5 A", C: "15.0 A", D: "30.0 A" }, answer: "C", explanation: "P_in = 7500 / 0.9 = 8333 W. I = P_in / (√3 × V_L × cos φ) = 8333 / (1.732 × 400 × 0.8) = 8333 / 554.2 ≈ 15.0 A. Forgetting efficiency gives 13.5 A; forgetting cos φ gives 12.0 A; both wrong." },
            { number: 5, prompt: "On a 50 Hz mains supply, a half-cycle takes:", options: { A: "5 ms", B: "10 ms", C: "20 ms", D: "100 ms" }, answer: "B", explanation: "Period T = 1/50 = 20 ms. Half-cycle = T/2 = 10 ms. Useful for interpreting RCD trip times: a 30 mA RCD must trip within 200 ms at I_∆n (i.e. within 10 half-cycles)." },
            { number: 6, prompt: "Phase angle φ in a series RL circuit where R = 50 Ω and X_L = 50 Ω is:", options: { A: "0°", B: "30°", C: "45°", D: "60°" }, answer: "C", explanation: "tan φ = X/R = 1, so φ = arctan(1) = 45°. Power factor cos φ = cos 45° = 0.707 lagging. Equal R and X always give 45° regardless of their absolute values." },
            { number: 7, prompt: "A three-phase 400 V star-connected resistive heater bank dissipates 24 kW. The line current is:", options: { A: "20 A", B: "34.6 A", C: "60 A", D: "104 A" }, answer: "B", explanation: "P = √3 × V_L × I_L (cos φ = 1 for resistive). I_L = P / (√3 × V_L) = 24000 / (1.732 × 400) = 24000 / 692.8 ≈ 34.6 A. The 60 A figure (C) divides 24000/400 (skips √3)." },
            { number: 8, prompt: "A poor power factor (e.g. 0.5) on a fixed-power load means:", options: { A: "Less true power is consumed", B: "Higher line current is needed for the same true power, increasing I²R losses and cable size", C: "Higher voltage is needed at the load", D: "Frequency falls" }, answer: "B", explanation: "For fixed P, I = P / (V × cos φ): halving cos φ doubles the current. Consequences: bigger cables, higher distribution losses, higher kVA demand, possible reactive-power penalty charges from the DNO. PF correction restores efficiency." }
          ]
        }
      ]
    },
    {
      id: "section-3",
      title: "Section 3 — Conductors, Cables & Voltage Drop",
      variants: [
        {
          id: "v1",
          questions: [
            { number: 1, prompt: "Approximate resistivity of copper at 20 °C is closest to:", options: { A: "1.72 × 10⁻⁸ Ωm", B: "2.82 × 10⁻⁸ Ωm", C: "1 × 10⁻⁶ Ωm", D: "1 × 10⁻⁴ Ωm" }, answer: "A", explanation: "Copper ρ ≈ 1.72 × 10⁻⁸ Ωm at 20 °C; aluminium ρ ≈ 2.82 × 10⁻⁸ Ωm. The lower resistivity of copper is the principal reason it is preferred for fine-cross-section wiring; aluminium remains common for large bulk runs where weight matters." },
            { number: 2, prompt: "A 50 m run of 2.5 mm² copper conductor has a resistance of approximately (use ρ = 1.72 × 10⁻⁸ Ωm):", options: { A: "0.034 Ω", B: "0.34 Ω", C: "3.4 Ω", D: "34 Ω" }, answer: "B", explanation: "R = ρL/A = 1.72 × 10⁻⁸ × 50 / 2.5 × 10⁻⁶ = 8.6 × 10⁻⁷ / 2.5 × 10⁻⁶ = 0.344 Ω. Quick sanity check: 1.5 mm² T+E line+CPC (R1+R2) is around 24 mΩ/m." },
            { number: 3, prompt: "Voltage drop in a circuit is calculated as V_drop = (mV/A/m × I × L) / 1000. For a 30 m run of cable rated 18 mV/A/m carrying 16 A, the voltage drop is approximately:", options: { A: "4.32 V", B: "8.64 V", C: "14.4 V", D: "86.4 V" }, answer: "B", explanation: "V_drop = (18 × 16 × 30) / 1000 = 8640 / 1000 = 8.64 V. On a 230 V supply this is about 3.76% — within the 5% combined limit for fixed equipment but above the 3% lighting limit (BS 7671 Appendix 4 / Section 525)." },
            { number: 4, prompt: "An aluminium conductor needs approximately how much more cross-sectional area than copper to achieve the same resistance per metre?", options: { A: "About 0.6 times", B: "Equal", C: "About 1.6 times", D: "About 4 times" }, answer: "C", explanation: "Resistivity ratio Al/Cu ≈ 2.82 / 1.72 ≈ 1.64. To match the same R/m, aluminium needs roughly 1.6× the area. Aluminium is therefore about half the weight per equivalent ampacity, which is why DNO service-cable cores are commonly aluminium." },
            { number: 5, prompt: "PVC-insulated cable is normally rated for a maximum continuous conductor temperature of:", options: { A: "60 °C", B: "70 °C", C: "90 °C", D: "150 °C" }, answer: "B", explanation: "PVC (Type 70) is rated 70 °C continuous conductor temperature. Thermosetting / XLPE (Type 90) is rated 90 °C. Sustained operation above the rated temperature accelerates insulation ageing and shortens cable life." },
            { number: 6, prompt: "The CPC of a typical 2.5/1.5 mm² T+E twin-and-earth cable has a cross-sectional area of:", options: { A: "1.0 mm²", B: "1.5 mm²", C: "2.5 mm²", D: "4 mm²" }, answer: "B", explanation: "The 'twin-and-earth' designation 2.5/1.5 means 2.5 mm² line and neutral conductors and a reduced 1.5 mm² CPC. Other common pairings: 1.5/1.0, 4/1.5, 6/2.5, 10/4." },
            { number: 7, prompt: "A 2.5 mm² T+E ring final circuit at 13 mV/A/m carries 18 A over 25 m of conductor (one direction). Voltage drop end-to-end (assuming worst case treats the run as a radial) is:", options: { A: "5.85 V", B: "8.45 V", C: "11.7 V", D: "29.3 V" }, answer: "A", explanation: "V_drop = (mV/A/m × I × L) / 1000 = (13 × 18 × 25) / 1000 = 5.85 V. In a properly working ring, end-to-end voltage drop is roughly half the radial figure because of the parallel feeds — but worst case treated as a radial gives the upper bound." },
            { number: 8, prompt: "Doubling the cable length, with current and conductor unchanged, will cause the voltage drop to:", options: { A: "Halve", B: "Stay the same", C: "Double", D: "Quadruple" }, answer: "C", explanation: "V_drop = (mV/A/m × I × L) / 1000 — proportional to L. Doubling length doubles voltage drop. (By contrast, doubling current also doubles drop, while doubling area roughly halves it.)" }
          ]
        },
        {
          id: "v2",
          questions: [
            { number: 1, prompt: "Resistance of a metallic conductor varies with temperature according to its temperature coefficient. For copper at room temperature this is approximately:", options: { A: "+0.0004 /°C", B: "+0.004 /°C", C: "+0.04 /°C", D: "−0.004 /°C" }, answer: "B", explanation: "Copper has a positive temperature coefficient α ≈ 0.004 /°C — resistance rises with temperature. R_t = R_20 [1 + α(t − 20)]. A 50 °C rise lifts copper resistance by ~20%, which matters for fault loop and voltage-drop calculations." },
            { number: 2, prompt: "If a 20 m length of conductor has a resistance of 0.1 Ω, the same conductor at 60 m (same area) would have a resistance of:", options: { A: "0.033 Ω", B: "0.1 Ω", C: "0.2 Ω", D: "0.3 Ω" }, answer: "D", explanation: "R ∝ L for fixed area and material; tripling the length triples the resistance: 0.1 × 3 = 0.3 Ω. Also, doubling the cross-sectional area halves the resistance for fixed length." },
            { number: 3, prompt: "Doubling the cross-sectional area of a conductor (keeping length fixed) will:", options: { A: "Halve the resistance", B: "Double the resistance", C: "Leave the resistance unchanged", D: "Quadruple the resistance" }, answer: "A", explanation: "R = ρL/A — resistance is inversely proportional to A. Doubling A halves R. Combined with the inverse-area relationship for current density, this is the basis of stepping up to a larger CSA when current or voltage drop demands it." },
            { number: 4, prompt: "A 6 mm² T+E cable has a tabulated voltage drop of about 7.3 mV/A/m. Carrying 32 A over 35 m, the voltage drop is approximately:", options: { A: "4.1 V", B: "8.2 V", C: "16.3 V", D: "82 V" }, answer: "B", explanation: "V_drop = (mV/A/m × I × L)/1000 = (7.3 × 32 × 35)/1000 = 8175/1000 ≈ 8.2 V. On 230 V this is 3.5% — comfortably under the 5% combined limit for fixed equipment." },
            { number: 5, prompt: "A 0.4 Ω cable resistance carries 25 A. The cable's I²R loss is:", options: { A: "10 W", B: "100 W", C: "250 W", D: "1000 W" }, answer: "C", explanation: "P = I²R = 625 × 0.4 = 250 W. Reducing the cable resistance (larger CSA) substantially reduces ongoing energy losses — relevant for long industrial runs and BS 7671 efficiency considerations." },
            { number: 6, prompt: "Thermosetting (XLPE / Type 90) cables are most useful in installations because:", options: { A: "They are cheaper than PVC", B: "They permit higher continuous conductor temperatures (90 °C) for the same insulation", C: "They are non-flammable", D: "They are mandatory in domestic dwellings" }, answer: "B", explanation: "Thermosetting cable insulations (e.g. XLPE) tolerate higher conductor temperatures, giving a higher current rating in the same CSA — a useful margin in hot environments or grouped installations. PVC is still mandated by some end-user specifications." },
            { number: 7, prompt: "Stranded conductors are normally used in flexible cables (e.g. 3-core flex) because:", options: { A: "Stranded copper has lower resistivity than solid copper", B: "Multiple thin strands flex repeatedly without work-hardening or breaking", C: "Stranding allows aluminium use", D: "Stranded cores carry more current per CSA" }, answer: "B", explanation: "Resistivity is the same for stranded and solid; the benefit of stranding is mechanical — flexibility and resistance to fatigue. Solid cores would crack under repeated flexing in trailing/portable cables." },
            { number: 8, prompt: "Cable selection for a circuit normally proceeds in the order:", options: { A: "Voltage drop → CCC after correction → fault rating → design current", B: "CCC → design current → fault rating → voltage drop", C: "Fault rating → design current → voltage drop → CCC", D: "Design current → CCC after correction factors → voltage drop check → fault-current rating check" }, answer: "D", explanation: "BS 7671's Appendix 4 / Section 433 design flow: determine I_b (design current), pick a protective device (I_n ≥ I_b), apply correction factors and select a CSA whose CCC ≥ I_n, then verify voltage drop and short-circuit (adiabatic) rating. The chosen size satisfies the largest demand of the four checks." }
          ]
        },
        {
          id: "v3",
          questions: [
            { number: 1, prompt: "Increasing ambient temperature around a cable from 30 °C to 40 °C will:", options: { A: "Increase its current-carrying capacity", B: "Have no effect", C: "Reduce its current-carrying capacity by applying a correction factor below 1", D: "Reduce voltage drop only" }, answer: "C", explanation: "Higher ambient temperature reduces the cable's heat-dissipation margin to its conductor temperature limit, so a derating factor (Ca, Appendix 4 BS 7671) below 1.0 must be applied. The same applies to thermal insulation around a cable and grouping with other current-carrying conductors." },
            { number: 2, prompt: "Voltage drop in a circuit is most directly reduced by:", options: { A: "Reducing the supply frequency", B: "Increasing the operating temperature", C: "Increasing the conductor cross-sectional area", D: "Adding more loads to the circuit" }, answer: "C", explanation: "V_drop ∝ ρL/A and ∝ I. Increasing A directly reduces R/m and therefore V_drop. The other choices either don't affect drop (frequency, on a resistive run) or worsen it (more current, hotter conductor)." },
            { number: 3, prompt: "Permitted voltage drop limits in BS 7671 (typical figures, low-voltage installations) for lighting and other circuits respectively are:", options: { A: "1% and 2%", B: "3% and 5%", C: "5% and 8%", D: "10% and 15%" }, answer: "B", explanation: "BS 7671 Appendix 4 / Section 525 indicates 3% for lighting and 5% for other uses (from the origin to the load) on direct LV supplies. Higher allowances apply for installations supplied via private transformers (~5%/8%)." },
            { number: 4, prompt: "A 1.5 mm² T+E cable installed in thermal insulation experiences a derating because:", options: { A: "Insulation increases the dielectric stress on the cable", B: "Insulation increases its capacitance", C: "Insulation reduces the cable's mechanical strength", D: "Insulation prevents heat dissipation, raising conductor temperature for the same current" }, answer: "D", explanation: "Thermal insulation traps the I²R heat in the conductor, lifting conductor temperature toward (or above) its rated maximum for a given current. The Reference Method / installation method must be selected with this in mind, with derating per Appendix 4." },
            { number: 5, prompt: "Two cables carry the same current. Cable A is 4 mm² copper; Cable B is 10 mm² aluminium. Which has the lower resistance per metre (R/m)?", options: { A: "Cable A (4 mm² copper)", B: "Both have the same R/m", C: "Cable B (10 mm² aluminium)", D: "Depends only on length" }, answer: "C", explanation: "R/m for copper = ρ/A = 1.72e-8 / 4e-6 = 4.30 mΩ/m. R/m for aluminium = 2.82e-8 / 10e-6 = 2.82 mΩ/m. The larger aluminium CSA more than compensates for its higher resistivity, so Cable B has the lower R/m." },
            { number: 6, prompt: "Voltage drop on a 30 m run of cable rated 11 mV/A/m carrying 25 A is:", options: { A: "4.13 V", B: "5.50 V", C: "8.25 V", D: "11 V" }, answer: "C", explanation: "V_drop = (11 × 25 × 30)/1000 = 8250/1000 = 8.25 V. On 230 V, that's 3.59% — a typical figure that frequently triggers the recommendation to step up by one CSA on long runs." },
            { number: 7, prompt: "Current density J in a 2.5 mm² conductor carrying 16 A is:", options: { A: "0.16 A/mm²", B: "1 A/mm²", C: "6.4 A/mm²", D: "40 A/mm²" }, answer: "C", explanation: "J = I/A = 16/2.5 = 6.4 A/mm². Copper conductors typically tolerate 4–7 A/mm² in installation conditions; pushing higher requires improved cooling, e.g. better installation method or shorter runs." },
            { number: 8, prompt: "Adiabatic equation for short-circuit verification gives the minimum CSA from S = √(I²t)/k. The 'k' value depends on:", options: { A: "Cable length and current", B: "Voltage drop and frequency", C: "Conductor material, insulation type and initial/final temperatures", D: "Earthing arrangement only" }, answer: "C", explanation: "The k coefficient (BS 7671 Table 43.1 etc.) reflects conductor material (Cu/Al), insulation (PVC/XLPE), and the initial/final temperature limits during fault. With copper and 70 °C PVC, k ≈ 115; copper and 90 °C thermosetting k ≈ 143." }
          ]
        },
        {
          id: "v4",
          questions: [
            { number: 1, prompt: "A 1 mm² CPC has a resistance per metre of approximately 18 mΩ/m at 20 °C. Combined R1 + R2 of a 30 m circuit (line + CPC same CSA) is then approximately:", options: { A: "0.54 Ω", B: "10.8 Ω", C: "0.27 Ω", D: "1.08 Ω" }, answer: "D", explanation: "R1 = R2 ≈ 30 × 0.018 Ω = 0.54 Ω. R1 + R2 = 0.54 + 0.54 = 1.08 Ω at 20 °C. Multiply by ~1.2 to estimate the value at operating temperature for fault loop and Zs purposes." },
            { number: 2, prompt: "Skin effect in AC conductors becomes significant at:", options: { A: "Mains frequency (50 Hz) for all CSAs", B: "Never in copper conductors", C: "Power frequencies for very large CSAs (e.g. above ~150 mm² copper)", D: "Only at radio frequencies" }, answer: "C", explanation: "At 50 Hz, skin effect is negligible up to large CSAs but starts to matter for very large copper conductors (above ~150 mm²) and for large aluminium conductors. Designers may use multiple smaller cables in parallel rather than one huge one to mitigate this." },
            { number: 3, prompt: "A cooker circuit is loaded at 32 A and run in 6 mm² T+E. The mV/A/m for 6 mm² T+E is around 7.3 mV/A/m. Over a 25 m run, voltage drop is:", options: { A: "5.84 V", B: "1.46 V", C: "11.7 V", D: "29.2 V" }, answer: "A", explanation: "V_drop = (7.3 × 32 × 25)/1000 = 5840/1000 = 5.84 V (~2.5% on 230 V). The 11.7 V figure (C) would be 50 m of cable, the 29.2 V figure 6 mm² × full radial length × 32 A but in error." },
            { number: 4, prompt: "An 'L' core in modern UK fixed-wiring T+E has the harmonised colour:", options: { A: "Red", B: "Green/yellow", C: "Blue", D: "Brown" }, answer: "D", explanation: "Single-phase fixed wiring: brown = line, blue = neutral, green/yellow = CPC. Pre-2006: red = line, black = neutral. Three-phase moved from red/yellow/blue to brown/black/grey." },
            { number: 5, prompt: "Voltage drop on a long lighting circuit can be reduced by stepping up the conductor. Replacing 1 mm² with 1.5 mm² (same length, same current) reduces the drop by approximately:", options: { A: "10%", B: "67%", C: "33%", D: "50%" }, answer: "C", explanation: "V_drop ∝ 1/A. New/old = 1/1.5 = 0.667 (about a 33% reduction). The actual mV/A/m figures (~29 mV/A/m for 1.0 mm² T+E vs ~19 mV/A/m for 1.5 mm² T+E) confirm the order of magnitude." },
            { number: 6, prompt: "On a long underground SWA cable run, the principal reason for choosing copper over aluminium for the same CCC is usually:", options: { A: "Cost: copper is cheaper", B: "Aluminium is not used in BS 7671", C: "Aluminium cannot be installed underground", D: "Smaller conductor for the same rating, easier termination" }, answer: "D", explanation: "For the same CCC, copper needs roughly 2/3 the CSA of aluminium. Smaller cable means smaller ducts, easier glanding, easier handling. Aluminium has cost advantages on long bulk runs and is often chosen there despite the larger CSA." },
            { number: 7, prompt: "An installation 'reference method' (e.g. 'B' clipped on a wall, 'C' in conduit, etc.) is significant because:", options: { A: "It determines the maximum CCC for a given cable size", B: "It determines the cable colour code", C: "It determines the voltage drop only", D: "It determines the earthing system" }, answer: "A", explanation: "Reference method (Appendix 4 BS 7671) sets the heat-dissipation environment and therefore the tabulated CCC. Same CSA can have very different ratings between methods (e.g. clipped direct vs buried in thermal insulation)." },
            { number: 8, prompt: "Using flexible cord rather than fixed-wiring T+E for a fixed appliance is acceptable when:", options: { A: "Always, as flex is more convenient", B: "Only in dwellings, never in commercial work", C: "Where the cord is connected via a fused connection unit and adequately supported, with the appliance's I_b within the flex's CCC", D: "Never — only solid-cored T+E is permitted" }, answer: "C", explanation: "Flex (e.g. 3-core 1.5 mm² butyl-rubber) can connect a fixed appliance via an FCU, provided it is mechanically supported, of adequate size for the appliance's design current, and protected against the foreseeable mechanical environment." }
          ]
        },
        {
          id: "v5",
          questions: [
            { number: 1, prompt: "A 100 m run of 6 mm² copper conductor at 20 °C has a resistance of approximately:", options: { A: "0.029 Ω", B: "29 Ω", C: "2.9 Ω", D: "0.29 Ω" }, answer: "D", explanation: "R = ρL/A = 1.72 × 10⁻⁸ × 100 / 6 × 10⁻⁶ = 1.72 × 10⁻⁶ / 6 × 10⁻⁶ = 0.287 Ω. Quick rule: 6 mm² copper is about 2.9 mΩ/m at 20 °C; 100 m gives ~0.29 Ω." },
            { number: 2, prompt: "A circuit operating at 70 °C conductor temperature has a resistance approximately what factor higher than at 20 °C?", options: { A: "0.8 ×", B: "1.0 × (no change)", C: "1.2 ×", D: "2.0 ×" }, answer: "C", explanation: "R_70 = R_20 × [1 + α(70 − 20)] = R_20 × [1 + 0.004 × 50] = R_20 × 1.20. Resistance rises by ~20% — used as the 'hot' multiplier when evaluating Zs at operating temperature." },
            { number: 3, prompt: "A 230 V single-phase circuit feeds a 16 A load over 40 m of 4 mm² T+E (mV/A/m ≈ 11). Voltage drop is:", options: { A: "1.76 V", B: "3.52 V", C: "7.04 V", D: "14.08 V" }, answer: "C", explanation: "V_drop = (11 × 16 × 40)/1000 = 7040/1000 = 7.04 V. 7.04/230 = 3.06%, slightly above the 3% lighting limit but within the 5% combined limit for fixed equipment." },
            { number: 4, prompt: "If the design current of a circuit is 25 A and the cable's tabulated CCC is 32 A, but four cables are grouped together and a grouping factor of 0.7 applies, the effective CCC of one cable is:", options: { A: "32 A — grouping does not apply", B: "22.4 A — derated, now insufficient for the load", C: "45.7 A — grouping increases the rating", D: "12.8 A — derated but still adequate" }, answer: "B", explanation: "Effective CCC = 32 × 0.7 = 22.4 A, which is now less than the design current of 25 A. The cable size must be increased — grouping derating regularly forces step-up in CSA in industrial trunking and tray installations." },
            { number: 5, prompt: "A cable with insulation rated 90 °C is used with overcurrent protection chosen on a 70 °C basis. The CCC of the cable should be taken from:", options: { A: "Always the 90 °C value", B: "Always the 70 °C value (matching the basis on which the device was selected)", C: "Geometric mean of the two", D: "Only the 90 °C value, with a derating factor" }, answer: "B", explanation: "When the cable's terminations or the rest of the installation are limited to 70 °C (e.g. accessory contact ratings), the cable's effective rating must be taken at 70 °C even if the insulation could withstand 90 °C." },
            { number: 6, prompt: "The voltage drop limit applicable to a circuit feeding heating equipment is normally:", options: { A: "1%", B: "3%", C: "5%", D: "10%" }, answer: "C", explanation: "BS 7671 Section 525 indicates 5% from the origin to load for non-lighting uses (heating, sockets, fixed equipment) on direct LV supplies. Lighting is 3%. Higher voltage drops compromise efficiency and equipment performance." },
            { number: 7, prompt: "A 100 A submain feeds a sub-board over 50 m. The maximum allowable voltage drop is 5% of 400 V three-phase. To stay within this, the cable should drop no more than:", options: { A: "5 V line-to-line", B: "11.5 V line-to-line", C: "20 V line-to-line", D: "115 V line-to-line" }, answer: "C", explanation: "5% of 400 V = 20 V line-to-line. Convert to mV/A/m allowance: V_drop = mV/A/m × I × L × √3 / 1000 (for three-phase line voltage); rearranging: mV/A/m ≤ 20 × 1000 / (100 × 50 × 1.732) = 20000/8660 ≈ 2.31. Designer would pick a CSA where the tabulated mV/A/m is at or below this." },
            { number: 8, prompt: "A circuit's I²t rating (let-through energy) is critical to:", options: { A: "Voltage drop calculations", B: "Short-circuit (adiabatic) verification of conductor CSA", C: "Power factor of the load", D: "Earthing system selection" }, answer: "B", explanation: "I²t is the energy let through by the protective device during a short circuit. It must not exceed k²S² (the cable's adiabatic limit). High prospective fault current with a slow device pushes I²t up and may force a larger cable CSA." }
          ]
        }
      ]
    },
    {
      id: "section-4",
      title: "Section 4 — Protection, Earthing & Practice Bank",
      variants: [
        {
          id: "v1",
          questions: [
            { number: 1, prompt: "A Type B MCB will trip magnetically (instantaneously) at a current of:", options: { A: "1.13 In to 1.45 In", B: "3 In to 5 In", C: "5 In to 10 In", D: "10 In to 20 In" }, answer: "B", explanation: "Type B MCB instantaneous trip = 3–5 × In (BS EN 60898). Type C = 5–10 × In; Type D = 10–20 × In. The 1.13–1.45 range relates to overload (long-time) tripping, not magnetic instantaneous." },
            { number: 2, prompt: "An RCD rated 30 mA protects against electric shock from contact with live parts because:", options: { A: "It interrupts the supply when load current exceeds 30 mA", B: "It detects an imbalance between line and neutral currents (residual current) and disconnects within fractions of a second at I_∆n", C: "It senses voltage and disconnects on overvoltage", D: "It senses temperature and disconnects on heat" }, answer: "B", explanation: "An RCD compares the sum of the currents in the supply conductors (toroid). If the imbalance exceeds the operating current, the RCD trips. A 30 mA RCD provides 'additional protection' under BS 7671 against direct contact." },
            { number: 3, prompt: "Discrimination (selectivity) between two protective devices in series is achieved when:", options: { A: "Both devices trip simultaneously on a downstream fault", B: "Only the upstream device trips, regardless of the fault location", C: "Only the device closest to the fault (downstream) operates, leaving healthy circuits live", D: "The downstream device disconnects first only on overcurrent and not on earth fault" }, answer: "C", explanation: "Discrimination/selectivity means that a fault on a downstream circuit is cleared by the device closest to the fault, leaving the rest of the installation live. Cascading fault levels and time-current characteristics must align — generally requires upstream device of higher rating with appropriate I²t and time delay." },
            { number: 4, prompt: "A TN-S earthing system is characterised by:", options: { A: "A separate earth conductor provided by the DNO from the substation neutral", B: "Combined neutral and earth in the supply, separated at the property", C: "An earth electrode at the property only", D: "No earth at all — IT system" }, answer: "A", explanation: "TN-S: separate Neutral and Earth conductors from the source (substation transformer star point), the earth typically returning through the supply cable's metallic sheath. TN-C-S/PME has the supply neutral and earth combined and split at the cut-out." },
            { number: 5, prompt: "On a TT system, the earth return path during an L-E fault is:", options: { A: "Through the supply neutral", B: "Through the customer's earth electrode, the soil mass, and the DNO's earth electrode at the substation", C: "Through the line conductor only", D: "Through any nearby gas pipe" }, answer: "B", explanation: "TT installations rely on the soil to complete the earth-fault loop, giving Ze values typically 20–200 Ω — too high for protective devices to operate on overcurrent alone, hence the need for an RCD as the principal means of fault protection." },
            { number: 6, prompt: "For a 30 mA RCD on a TT installation, the maximum allowable earth electrode resistance to ensure disconnection within the touch-voltage limit (50 V) is theoretically:", options: { A: "5 Ω", B: "200 Ω", C: "1666 Ω", D: "5000 Ω" }, answer: "C", explanation: "Ra × IΔn ≤ 50 V → Ra ≤ 50 / 0.03 = 1666 Ω. In practice 200 Ω is used as the maximum to accommodate seasonal soil-resistance variation, so the rule of thumb says 'aim for under 200 Ω, never above 1666 Ω'." },
            { number: 7, prompt: "A 'broken PEN' on a TN-C-S supply is a particular hazard because:", options: { A: "It causes lights to flicker", B: "It can cause the metallic exposed-conductive-parts of the installation to rise to dangerous voltages relative to true earth", C: "It only causes overcurrent on the line conductor", D: "It is automatically detected by the consumer unit's main switch" }, answer: "B", explanation: "If the supply PEN conductor breaks, customer's load currents return via the earth bonded metalwork. Exposed-conductive-parts can rise toward line voltage relative to true earth, creating a serious shock and fire risk. Open-PEN protection devices (or earth-electrode TT for charging EVs) mitigate this." },
            { number: 8, prompt: "The three principal roles of protective devices in a circuit are:", options: { A: "Switching, isolation, indicating", B: "Overload protection, fault-current protection and additional protection (RCD)", C: "Voltage drop, voltage regulation, voltage limiting", D: "Phase rotation, frequency, harmonic" }, answer: "B", explanation: "BS 7671 Chapters 41–43: protective devices must provide (a) overload protection, (b) fault-current (short-circuit / earth-fault) protection, and (c) additional protection (typically a 30 mA RCD) where required. The same physical device may satisfy multiple roles." }
          ]
        },
        {
          id: "v2",
          questions: [
            { number: 1, prompt: "An RCBO combines:", options: { A: "Overload + over-voltage protection", B: "Overload + short-circuit protection (MCB) plus residual-current protection (RCD)", C: "Voltage and frequency monitoring", D: "Switching and isolation only" }, answer: "B", explanation: "An RCBO is a single device combining MCB-style overcurrent protection (overload + short-circuit) with RCD-style residual-current detection. Compared to a shared 30 mA RCD on a circuit group, RCBOs limit nuisance loss of supply when one circuit faults." },
            { number: 2, prompt: "Type C MCBs are typically chosen for:", options: { A: "Inductive loads with moderate inrush such as fluorescent banks, small motors and EV charging", B: "Resistive lighting circuits", C: "Heating circuits only", D: "Three-phase distribution boards only" }, answer: "A", explanation: "Type B MCBs (3–5 In magnetic) suit resistive loads. Type C (5–10 In) tolerate the inrush of small motors, fluorescent ballasts and similar inductive loads. Type D (10–20 In) suit transformer-energising and heavy-inductive starting." },
            { number: 3, prompt: "On a TN-C-S (PME) system, the typical Ze (external earth-fault loop impedance) is around:", options: { A: "0.35 Ω", B: "0.05 Ω", C: "0.8 Ω", D: "20 Ω" }, answer: "A", explanation: "TN-C-S typical declared Ze ≈ 0.35 Ω. TN-S typical ≤ 0.8 Ω. TT typically tens of ohms (often 20–200 Ω). Lower Ze allows larger fault currents and faster operation of fault-protection devices." },
            { number: 4, prompt: "Touch voltage limit considered safe under fault conditions for AC systems in BS 7671 (conventional UC) is:", options: { A: "12 V", B: "25 V", C: "50 V", D: "120 V" }, answer: "C", explanation: "BS 7671 takes 50 V_AC RMS as the conventional touch-voltage limit (UC) for normal dry conditions. Reduced UC (e.g. 25 V) applies in livestock/agricultural locations and other special environments." },
            { number: 5, prompt: "An RCD trips at I_∆n. To meet BS EN 61008/61009 requirements, a 30 mA RCD must operate at I_∆n within:", options: { A: "10 ms", B: "40 ms", C: "300 ms", D: "1 s" }, answer: "C", explanation: "Type AC/A general-purpose RCDs must operate within 300 ms at I_∆n; at 5 × I_∆n the trip time must be within 40 ms. 'Type S' (selective/time-delayed) RCDs have longer permitted trip times to allow downstream RCD discrimination." },
            { number: 6, prompt: "BS 88-3 fuses (HBC fuselink) are commonly used in:", options: { A: "Domestic consumer units only", B: "Emergency lighting only", C: "Plug tops", D: "Industrial distribution boards and supply heads, where high breaking capacity is needed" }, answer: "D", explanation: "BS 88-3 (formerly BS 88) HBC fuselinks have very high breaking capacity (typically 80 kA) and are common in supply heads, sub-distribution boards and high-fault industrial installations. BS 1362 fuses go in plugtops; BS 1361 fuses are commonly used in service-cutout positions." },
            { number: 7, prompt: "On an installation with a high prospective fault current (PFC), the protective device must have a breaking capacity:", options: { A: "Equal to or greater than the PFC", B: "Below the PFC (so it opens slowly)", C: "Equal to In", D: "Equal to the supply voltage" }, answer: "A", explanation: "If a fault current exceeds the device's breaking capacity, the device cannot safely interrupt and may explosively fail. BS 7671 requires the breaking capacity (Icn or Icu) to equal or exceed the PFC at the device's location." },
            { number: 8, prompt: "An IT system is characterised by:", options: { A: "Supply with no intentional earth reference (or earthed through high impedance), exposed-conductive parts earthed locally", B: "Both supply and customer earthed via separate electrodes", C: "Combined N+E throughout", D: "Three live conductors and no earth at all" }, answer: "A", explanation: "IT systems isolate the supply from earth (or use a high-impedance earth at the source). The first earth fault simply produces an alarm; only a second fault becomes hazardous. IT is uncommon in the UK except for medical, control and continuity-critical applications." }
          ]
        },
        {
          id: "v3",
          questions: [
            { number: 1, prompt: "30 mA RCD additional protection is required by BS 7671 for which of the following in a domestic dwelling?", options: { A: "Lighting circuits in bedrooms only", B: "Boiler circuits only", C: "Cooker circuits only", D: "Socket-outlets up to 32 A intended for general use, mobile equipment used outdoors and circuits in special locations" }, answer: "D", explanation: "BS 7671 Chapter 41/Section 411.3.3 requires 30 mA additional protection for general-use socket-outlets up to 32 A, mobile equipment used outdoors, and within special locations (zones 0/1/2 of bath/shower rooms). Most circuits in dwellings now require RCD protection regardless." },
            { number: 2, prompt: "The current-time characteristic of an MCB or fuse is described by:", options: { A: "An inverse-time relationship: higher overcurrents trip more quickly", B: "A vertical step at exactly In", C: "Constant trip time regardless of current", D: "Trip time proportional to voltage" }, answer: "A", explanation: "Inverse time-current curves: higher fault currents disconnect proportionally faster. The thermal element handles overload (slow); the magnetic element handles short-circuit (instantaneous, in tens of milliseconds at the magnetic threshold)." },
            { number: 3, prompt: "An earth fault on a TN-C-S installation completes its loop primarily through:", options: { A: "The customer's earth electrode and soil", B: "Bonding to nearby exposed-conductive-parts only", C: "The gas pipe", D: "The supply line + the supply neutral / PEN conductor returning to the substation transformer" }, answer: "D", explanation: "On TN-C-S/PME, the earth-fault current flows from the line conductor, through the fault, into the customer's CPC, into the main earthing terminal, into the supply neutral (PEN), and back to the source transformer. The low-impedance return permits rapid disconnection by overcurrent devices." },
            { number: 4, prompt: "A BS 1362 fuse (used in 13 A plug tops) is:", options: { A: "An MCB", B: "A semiconductor device", C: "A high breaking capacity cartridge fuse rated to 6 kA breaking capacity", D: "A rewireable fuse" }, answer: "C", explanation: "BS 1362 cartridge fuses (1 A – 13 A) protect the flexible cord of plug-connected equipment. Breaking capacity is 6 kA at 240 V — adequate for typical domestic supplies. The cartridge type prevents tampering and gives consistent performance." },
            { number: 5, prompt: "On an installation Zs is measured at 0.6 Ω. The expected fault current at the load is:", options: { A: "138 A", B: "230 A", C: "667 A", D: "383 A" }, answer: "D", explanation: "I_F = U₀ / Zs = 230 / 0.6 ≈ 383 A. Compare with the device's instantaneous trip threshold to confirm disconnection within the required time (e.g. 0.4 s for final circuits ≤ 32 A on TN systems)." },
            { number: 6, prompt: "The maximum disconnection time required by BS 7671 for a 230 V TN final circuit ≤ 32 A is:", options: { A: "0.04 s", B: "5 s", C: "1 s", D: "0.4 s" }, answer: "D", explanation: "BS 7671 Table 41.1: maximum disconnection time for final circuits ≤ 32 A on a 230 V TN system is 0.4 s. Distribution circuits and final circuits > 32 A may have up to 5 s. TT systems also require 0.2 s for final circuits ≤ 32 A by RCD." },
            { number: 7, prompt: "Why is the supplementary equipotential bonding sometimes still required in bathrooms even when 30 mA RCD additional protection is in place?", options: { A: "Because RCDs are unreliable", B: "Bathrooms always require supplementary bonding regardless", C: "Where the disconnection time, continuity of CPCs or main bonding cannot be confirmed, supplementary bonding ensures touch-voltage stays within safe limits between simultaneously-accessible parts", D: "Because of harmonics" }, answer: "C", explanation: "BS 7671 Section 701 generally permits omission of supplementary bonding in bath/shower rooms where main protective bonding, RCD additional protection and 0.4 s disconnection are all confirmed. Where any of these can't be relied on, supplementary bonding remains essential." },
            { number: 8, prompt: "A device labelled 'Type AC' RCD detects:", options: { A: "Sinusoidal AC residual currents only", B: "AC + pulsating DC residual currents", C: "AC + smooth DC residual currents", D: "Only DC residual currents" }, answer: "A", explanation: "Type AC: sinusoidal AC only. Type A: AC + pulsating DC (typical of electronic loads). Type F: AC + pulsating DC + 1 kHz components. Type B: AC + pulsating DC + smooth DC. EV charge points often need Type A with DC fault detection or Type B." }
          ]
        },
        {
          id: "v4",
          questions: [
            { number: 1, prompt: "An electrician needs to confirm that a 32 A Type B MCB will disconnect a 230 V final circuit within 0.4 s. The maximum permitted Zs is approximately (using U₀ ÷ I_a where I_a = 5 In):", options: { A: "0.36 Ω", B: "0.72 Ω", C: "1.44 Ω", D: "7.19 Ω" }, answer: "C", explanation: "Type B trips magnetically up to 5 × In = 5 × 32 = 160 A. Maximum Zs = U₀ / I_a = 230/160 = 1.44 Ω. This is the upper bound for instantaneous disconnection within the 0.4 s required for ≤32 A final circuits on TN." },
            { number: 2, prompt: "Series-parallel discrimination between a 100 A upstream HBC fuse and a 32 A downstream MCB on a 230 V circuit relies on:", options: { A: "Both devices having the same characteristic curve", B: "Manual switching", C: "The upstream fuse being slower to trip than the downstream MCB at all currents", D: "The downstream MCB's I²t (let-through energy) being less than the fuse's pre-arcing I²t at all expected fault currents" }, answer: "D", explanation: "Discrimination requires the downstream device's I²t (let-through energy) to be entirely below the upstream device's pre-arcing I²t curve over the full prospective fault range. Manufacturers publish discrimination tables to confirm this." },
            { number: 3, prompt: "Electric shock from a 230 V supply may cause 'let-go' difficulty at currents around:", options: { A: "1 mA", B: "5 mA", C: "10 mA", D: "100 mA" }, answer: "C", explanation: "1 mA: perception threshold. 5 mA: painful, no muscular tetany typically. 10–15 mA: 'let-go' threshold — muscular contraction prevents release. 50 mA+: respiratory effects. 100 mA+: ventricular fibrillation likely. The 30 mA RCD trip level is well below the fibrillation threshold for short exposure." },
            { number: 4, prompt: "A BS 3036 'rewireable' fuse compared to a modern MCB is generally:", options: { A: "Slower, less accurate, and may operate at a higher fault current threshold", B: "Faster to operate and more accurate", C: "Identical performance", D: "More expensive" }, answer: "A", explanation: "BS 3036 rewireable fuses (Class 4) are slower and less precise than modern MCBs/HBC fuses. The rated current is also a 'fusing factor' of 1.5–2 above the rated In. The 0.725 derating factor (Cf) was applied to cables protected by them — a frequent reason why older installations need upgrading." },
            { number: 5, prompt: "Earth electrode resistance Ra of 250 Ω, an installation with TT, 30 mA RCD. Touch voltage during earth fault is:", options: { A: "7.5 V", B: "5 V", C: "50 V", D: "230 V" }, answer: "A", explanation: "Voltage on exposed parts during fault = Ra × I_∆n = 250 × 0.03 = 7.5 V — well within the 50 V conventional touch-voltage limit. The 1666 Ω theoretical limit is set so that even at trip current the touch voltage stays under 50 V." },
            { number: 6, prompt: "A motor circuit is protected by a Type C MCB rated 16 A. The instantaneous trip threshold is between:", options: { A: "16 A and 32 A", B: "48 A and 80 A", C: "80 A and 160 A", D: "160 A and 320 A" }, answer: "C", explanation: "Type C: 5–10 × In. For In = 16 A, the magnetic threshold is between 80 A and 160 A. The motor's starting current (typically 6–7 × FLC) sits below the upper limit, avoiding nuisance trips on start." },
            { number: 7, prompt: "An RCD acts in conjunction with the conductor's automatic disconnection of supply (ADS) only when:", options: { A: "Used as a main switch on a domestic dwelling", B: "Connected upstream of all the circuits and tested at I_∆n", C: "The system's earth-fault loop impedance is too high for the overcurrent device alone to disconnect within the required time", D: "An overload occurs" }, answer: "C", explanation: "On TT systems and certain TN circuits with high Zs, the overcurrent device cannot achieve disconnection within the required time. An RCD provides the necessary fast disconnection through residual-current detection — the principal means of fault protection in those cases." },
            { number: 8, prompt: "Selectivity (discrimination) between 30 mA and 100 mA RCDs in series requires the upstream RCD to be:", options: { A: "A general-type 100 mA RCD", B: "A non-RCD device", C: "Identical to the downstream device", D: "A 'Type S' or selective time-delayed 100 mA RCD" }, answer: "D", explanation: "General-purpose RCDs trip in milliseconds and would not discriminate between two devices in series. The upstream device must be a 'Type S' (selective, time-delayed) RCD that allows the downstream RCD to clear its faults first; otherwise both trip simultaneously." }
          ]
        },
        {
          id: "v5",
          questions: [
            { number: 1, prompt: "A 16 A MCB Type B has a Zs that gives a fault current of 100 A. Will it disconnect within the 0.4 s requirement for a 230 V final circuit?", options: { A: "Yes — fault current exceeds the magnetic threshold", B: "No — fault current is below the magnetic threshold (5 × 16 = 80 A is exceeded, but the device may still operate on thermal time)", C: "It depends on the prospective fault current at origin", D: "Only if RCD is also fitted" }, answer: "A", explanation: "Type B magnetic trip threshold = 3–5 × In, so 16 A In = 48–80 A magnetic. A fault current of 100 A is comfortably above 80 A so instantaneous magnetic operation is achieved (within ~10 ms); 0.4 s is easily met." },
            { number: 2, prompt: "Earth fault loop impedance Zs is the sum of:", options: { A: "Ze + R1 + R2 (external + line + CPC)", B: "Ze + Rn (external + neutral)", C: "Just R1", D: "Ze divided by 2" }, answer: "A", explanation: "Zs = Ze + (R1 + R2). Ze is the external loop impedance from the supply; R1 + R2 is the resistance of the line conductor and CPC at the maximum point (furthest accessory). Designers calculate Zs at design-time and verify by measurement at end-of-job." },
            { number: 3, prompt: "Which earthing system is least suitable for a customer with sensitive electronics, due to potential transient voltages on the PEN conductor?", options: { A: "TN-C-S (PME)", B: "TN-S", C: "TT", D: "IT" }, answer: "A", explanation: "TN-C-S/PME systems combine N+E in the supply, so neutral disturbances appear on customer earth and may inject noise into sensitive equipment. TN-S provides cleaner earth; some installations specify a TN-S or TT 'equipotential' earth for IT loads instead." },
            { number: 4, prompt: "A circuit has a 6 A Type B MCB. The Type B magnetic instantaneous trip threshold range is:", options: { A: "18 A to 30 A", B: "6 A to 18 A", C: "30 A to 60 A", D: "60 A to 120 A" }, answer: "A", explanation: "Type B: magnetic trip = 3–5 × In. For In = 6 A, range = 18–30 A. Useful for evaluating whether the MCB will trip on a particular fault scenario or whether the cable's R1+R2 needs reducing." },
            { number: 5, prompt: "An RCBO is preferred over a shared 30 mA RCD upstream of multiple MCBs because:", options: { A: "RCBOs limit the loss of supply on a fault to a single circuit, improving discrimination and reducing nuisance loss", B: "RCBOs cost less", C: "RCBOs avoid the need for any earthing", D: "RCBOs do not need testing" }, answer: "A", explanation: "Shared 30 mA RCDs disconnect every circuit on their group when any one circuit faults. RCBOs trip only the affected circuit, leaving the rest of the installation live — a significant safety and continuity benefit, especially for fridges, alarms and lighting." },
            { number: 6, prompt: "On 230 V supplies, the typical effect of a 50 mA shock for over 1 second is:", options: { A: "Painful contractions and possible respiratory paralysis", B: "Mild discomfort only", C: "Possible immediate cardiac fibrillation", D: "No effect" }, answer: "A", explanation: "50 mA prolonged: severe muscular contraction, respiratory paralysis, and risk of fibrillation if exposure continues. The 30 mA RCD trip threshold is set well below this so that any shock is interrupted before fibrillation becomes likely." },
            { number: 7, prompt: "When measuring Zs by line-earth loop test on an RCD-protected circuit, the test method should be:", options: { A: "RCD-friendly (no-trip) test, or temporarily bypass the RCD with care", B: "High-current method, ignoring the RCD", C: "Only DC measurement", D: "Insulation resistance test instead" }, answer: "A", explanation: "Modern testers offer an RCD-friendly Zs measurement that injects current below the RCD trip threshold, avoiding nuisance trips. Alternatively, temporarily disconnect the RCD or test upstream of it. Bypassing live RCDs requires safe-isolation discipline." },
            { number: 8, prompt: "Adiabatic check confirms that on a fault, the conductor's:", options: { A: "Voltage drop stays within 5%", B: "Operating temperature stays below 30 °C", C: "Frequency response is preserved", D: "Cross-section is sufficient to absorb fault energy without exceeding its insulation's permitted final temperature" }, answer: "D", explanation: "Adiabatic equation S ≥ √(I²t)/k checks that the conductor can absorb the fault's let-through energy without rising above the insulation's permitted maximum (160 °C for PVC, 250 °C for thermosetting). Assumes no heat loss during the fault." }
          ]
        }
      ]
    },
    {
      id: "section-5-merged-fundamentals",
      title: "Section 5 — Merged Electrical Fundamentals",
      variants: [
        {
          id: "v1",
          questions: [
            { number: 1, prompt: "A three-phase 400 V motor draws 12 A line current at 0.85 lagging power factor. Its input true power is approximately:", options: { A: "4.08 kW", B: "5.76 kW", C: "7.07 kW", D: "8.31 kW" }, answer: "C", explanation: "P = √3 × V_L × I_L × cos φ = 1.732 × 400 × 12 × 0.85 = 7066 W ≈ 7.07 kW. The 8.31 kW figure (D) is apparent power VA × cos φ done wrongly; 5.76 kW skips the √3 entirely." },
            { number: 2, prompt: "A 30 m run of 6 mm² T+E (mV/A/m ≈ 7.3) carries 16 A. Voltage drop is approximately:", options: { A: "1.75 V", B: "3.50 V", C: "7.00 V", D: "10.5 V" }, answer: "B", explanation: "V_drop = (7.3 × 16 × 30)/1000 = 3504/1000 = 3.50 V. On 230 V that's 1.52% — well within both lighting (3%) and general (5%) limits, and a safe choice for a sub-circuit at this length." },
            { number: 3, prompt: "On a TT installation Ze = 50 Ω. (R1 + R2) of a final circuit is 0.4 Ω. Zs is approximately:", options: { A: "0.4 Ω", B: "12.5 Ω", C: "50.4 Ω", D: "200 Ω" }, answer: "C", explanation: "Zs = Ze + (R1 + R2) = 50 + 0.4 = 50.4 Ω. On TT, Ze dominates Zs. Such a high Zs cannot rely on overcurrent protection for ADS — the RCD becomes the principal fault-protection device." },
            { number: 4, prompt: "Doubling cable length doubles voltage drop and doubles loop impedance. The fault current at the far end therefore changes by a factor of:", options: { A: "Doubled", B: "Halved", C: "Stays the same", D: "Quartered" }, answer: "B", explanation: "I_F = U₀ / Zs. If Zs doubles, I_F halves. This is why long runs are vulnerable to failing the maximum Zs check — a key reason for stepping up CSA on long sub-circuits even when voltage drop is acceptable." },
            { number: 5, prompt: "An installation has Ze = 0.35 Ω (TN-C-S). A 32 A B-type MCB final circuit has (R1+R2) = 0.65 Ω. The Zs is 1.0 Ω. The fault current and likely disconnection time are:", options: { A: "230 A and 0.4 s", B: "100 A and 5 s", C: "800 A and 0.1 s", D: "Insufficient data" }, answer: "A", explanation: "I_F = 230/1.0 = 230 A. Type B 32 A magnetic threshold = 5 × 32 = 160 A; 230 A exceeds it, so instantaneous magnetic operation (within 100 ms) gives disconnection well within the required 0.4 s." },
            { number: 6, prompt: "Compared to TN-S, the TT system has:", options: { A: "Lower Ze and faster overcurrent disconnection", B: "Higher Ze, requiring RCD-based fault protection", C: "Combined N+E in the supply", D: "No earth at all" }, answer: "B", explanation: "TT relies on a customer earth electrode in soil; Ze is typically tens of ohms, far too high for overcurrent devices to clear earth faults. RCDs (typically 100 mA upfront, 30 mA per circuit) provide the required disconnection." },
            { number: 7, prompt: "A 230 V 1.2 kW heater has a measured insulation resistance of 1 MΩ between L and earth. The earth-fault current under normal operating voltage would be approximately:", options: { A: "0.23 µA", B: "0.23 mA", C: "23 mA", D: "1 A" }, answer: "B", explanation: "I = V/R = 230 / 1,000,000 = 0.00023 A = 0.23 mA. BS 7671 minimum IR for 500 V test is 1 MΩ for low-voltage circuits — at this minimum, earth-leakage is well below the 30 mA RCD threshold but represents the lower bound of acceptable insulation health." },
            { number: 8, prompt: "A balanced three-phase resistive load on a 400 V supply dissipates 30 kW. The line current is:", options: { A: "25 A", B: "43.3 A", C: "75 A", D: "130 A" }, answer: "B", explanation: "Resistive (cos φ = 1): P = √3 × V_L × I_L → I_L = 30000 / (1.732 × 400) = 30000/692.8 ≈ 43.3 A. The 75 A figure forgets the √3; 25 A applies a √3 incorrectly in the divisor." }
          ]
        },
        {
          id: "v2",
          questions: [
            { number: 1, prompt: "An immersion heater rated 3 kW at 230 V is connected via 2.5 mm² T+E (mV/A/m ≈ 18) over 18 m. The voltage drop on the supply cable is approximately:", options: { A: "2.11 V", B: "4.23 V", C: "6.34 V", D: "10.6 V" }, answer: "B", explanation: "I = P/V = 3000/230 = 13 A. V_drop = (18 × 13 × 18)/1000 = 4212/1000 = 4.22 V (~1.83% of 230 V). Comfortably within the 5% general-use limit." },
            { number: 2, prompt: "A 230 V single-phase domestic supply has Ze = 0.35 Ω (TN-C-S declared). Adding (R1+R2) = 0.45 Ω at the load end of a circuit, the fault current at full operating temperature (×1.2 hot multiplier) is approximately:", options: { A: "192 A", B: "239 A", C: "288 A", D: "345 A" }, answer: "B", explanation: "Cold Zs = 0.35 + 0.45 = 0.80 Ω. Hot Zs ≈ 0.35 + (0.45 × 1.2) = 0.35 + 0.54 = 0.89 Ω. Using simplified hot Zs ≈ 0.96 Ω is also reasonable; I_F = 230/0.96 ≈ 240 A. Variation around 230–240 A; the closest answer is 239 A." },
            { number: 3, prompt: "A 30 m run of 4 mm² T+E (mV/A/m ≈ 11) is to feed a 25 A load. The voltage drop is:", options: { A: "4.13 V", B: "8.25 V", C: "16.5 V", D: "33 V" }, answer: "B", explanation: "V_drop = (11 × 25 × 30)/1000 = 8250/1000 = 8.25 V (~3.59% of 230 V). Above the 3% lighting limit, within the 5% general-use limit. Stepping up to 6 mm² (mV/A/m ≈ 7.3) would drop this to 5.48 V." },
            { number: 4, prompt: "On a 400 V three-phase supply, the line current of a 22 kW motor at 0.8 PF and 88% efficiency is approximately:", options: { A: "31.7 A", B: "39.6 A", C: "45.0 A", D: "57.5 A" }, answer: "C", explanation: "P_in = P_out / η = 22000 / 0.88 = 25000 W. I_L = P_in / (√3 × V_L × cos φ) = 25000 / (1.732 × 400 × 0.8) = 25000 / 554.2 ≈ 45 A. Forgetting efficiency gives 39.6 A; forgetting cos φ gives 36 A; both wrong." },
            { number: 5, prompt: "Compared to TN-S, a TT installation requires:", options: { A: "Smaller cable CSA", B: "Mandatory RCD as principal fault-protection device, with relatively low Ra", C: "No earth at all", D: "A higher voltage" }, answer: "B", explanation: "TT systems are characterised by a high Ze (the soil completes the loop). RCDs (typically 100 mA selective upfront and 30 mA per circuit) become the principal means of meeting BS 7671's required disconnection times. Ra should be kept low and stable enough for reliable operation." },
            { number: 6, prompt: "An EICR records Zs at the furthest socket on a final circuit as 1.32 Ω. The OPD is a 32 A Type B MCB. Acceptable maximum Zs (BS 7671 Table 41.3 typical) is around:", options: { A: "0.8 Ω", B: "1.15 Ω", C: "1.44 Ω", D: "2.4 Ω" }, answer: "C", explanation: "Maximum Zs for B32 (BS 7671 typical figures): around 1.44 Ω at U₀ = 230 V (with the 0.95 voltage factor and Cmin/Cmax conventions, sometimes 1.37 Ω). The measured 1.32 Ω is below the 1.44 Ω limit so the circuit is compliant." },
            { number: 7, prompt: "A 9 kW shower fed by 10 mm² T+E (mV/A/m ≈ 4.4) over 25 m draws 39 A. Voltage drop is approximately:", options: { A: "2.14 V", B: "4.29 V", C: "8.58 V", D: "17.16 V" }, answer: "B", explanation: "V_drop = (4.4 × 39 × 25)/1000 = 4290/1000 = 4.29 V (~1.87% of 230 V). 10 mm² is a common choice for 9–10 kW domestic showers; the headroom on V_drop accommodates longer runs." },
            { number: 8, prompt: "A delta-connected 400 V three-phase 30 kW resistive load draws a phase current of:", options: { A: "25 A", B: "43.3 A", C: "75 A", D: "130 A" }, answer: "A", explanation: "Total P = 3 × V_ph × I_ph (delta has V_ph = V_L = 400). 30000 = 3 × 400 × I_ph → I_ph = 25 A. Line current would be I_L = √3 × I_ph = 43.3 A (same as a star configuration)." }
          ]
        },
        {
          id: "v3",
          questions: [
            { number: 1, prompt: "A 230 V kettle is rated 2.4 kW. The cold (room-temperature) element resistance, before warming, is approximately:", options: { A: "5.5 Ω", B: "11 Ω", C: "22 Ω", D: "44 Ω" }, answer: "C", explanation: "R = V²/P = 230²/2400 = 52900/2400 ≈ 22.0 Ω at hot operating temperature; cold element will be slightly lower, but this is the headline working value taken from the rating plate. The 11 Ω would have been V/P (wrong)." },
            { number: 2, prompt: "On a TN-C-S installation, an EV charge-point is to be installed outdoors. The DNO does not permit the use of the supply earth for the charge point. The acceptable solution is:", options: { A: "Install on the existing supply earth and add a 30 mA RCD", B: "Provide a TT earth for the charge point (separate earth electrode) or install an open-PEN protection device", C: "Avoid all earthing — use a Class II charging unit only", D: "Use a 100 mA upstream RCD" }, answer: "B", explanation: "Outdoor EV charge-points on TN-C-S risk dangerous touch voltages on the vehicle's chassis if the supply PEN breaks. Solutions: provide a separate TT electrode for the EV circuit, or use an approved open-PEN protection device that disconnects on detected PEN voltage rise. Section 722 / Section 411.4.2 BS 7671 covers this." },
            { number: 3, prompt: "A 50 m three-phase submain in 16 mm² 4-core SWA (mV/A/m ≈ 2.7 line-to-line) carries 50 A. Voltage drop is:", options: { A: "3.4 V line-to-line", B: "6.75 V line-to-line", C: "13.5 V line-to-line", D: "27 V line-to-line" }, answer: "B", explanation: "V_drop = (2.7 × 50 × 50)/1000 = 6750/1000 = 6.75 V line-to-line (~1.7% of 400 V). For three-phase, the tabulated mV/A/m is typically the line-to-line figure already." },
            { number: 4, prompt: "A 32 A radial circuit in 4 mm² T+E feeds a workshop. The circuit is grouped with three other circuits in a common conduit (Cg = 0.65) and runs through 1 m of thermal insulation (Ci factor not applied to short lengths). Effective CCC of the cable starting from a Method C 36 A tabulated rating is:", options: { A: "23.4 A — insufficient", B: "32 A — adequate", C: "36 A — adequate", D: "41 A — adequate" }, answer: "A", explanation: "Effective CCC = 36 × 0.65 = 23.4 A — below the design current of 32 A. The cable would either need to be upsized or the grouping reduced. This kind of compounding drives many real-world cable upgrades." },
            { number: 5, prompt: "An operator's hand-to-hand body resistance under dry conditions is around 1500 Ω. Touching a 230 V live conductor would draw approximately:", options: { A: "1.5 mA", B: "15 mA", C: "150 mA", D: "1.5 A" }, answer: "C", explanation: "I = V/R = 230/1500 ≈ 153 mA. Well above the 100 mA fibrillation threshold, so this is potentially fatal in seconds without intervention. Wet skin reduces body resistance by an order of magnitude, making 230 V even more dangerous." },
            { number: 6, prompt: "A 10 mm² T+E ring final circuit (mV/A/m ≈ 4.4) has a total length of 60 m, with the load drawing 25 A at the midpoint. Approximate voltage drop at the midpoint, treating each leg as carrying half the load over 30 m, is:", options: { A: "0.83 V", B: "1.65 V", C: "3.30 V", D: "6.60 V" }, answer: "B", explanation: "Each leg: I/2 = 12.5 A over 30 m. V_drop per leg = (4.4 × 12.5 × 30)/1000 = 1.65 V. Both legs experience the same drop (parallel paths), so the load sees 1.65 V — a key design advantage of ring circuits over radials at the midpoint." },
            { number: 7, prompt: "Doubling a single-phase load's power at fixed voltage will:", options: { A: "Halve the current", B: "Leave the current unchanged", C: "Double the current", D: "Quadruple the current" }, answer: "C", explanation: "P = VI; if V is fixed and P doubles, I doubles. Cable I²R losses, however, quadruple — illustrating why long cables limit how much load can be added without uprating CSA." },
            { number: 8, prompt: "A 400 V three-phase load draws 50 A line current at 0.92 lagging power factor. The reactive power Q is approximately:", options: { A: "13.6 kVAr", B: "26 kVAr", C: "32 kVAr", D: "13.5 kVA" }, answer: "A", explanation: "S = √3 × V_L × I_L = 1.732 × 400 × 50 = 34640 VA ≈ 34.64 kVA. sin φ = √(1 − 0.92²) = √(1 − 0.8464) = √0.1536 ≈ 0.392. Q = S × sin φ = 34.64 × 0.392 ≈ 13.6 kVAr." }
          ]
        },
        {
          id: "v4",
          questions: [
            { number: 1, prompt: "A 230 V single-phase ring final circuit drawn at 32 A has a measured (R1+R2) of 0.5 Ω in cold conditions. Estimated hot Zs (with Ze = 0.35 Ω TN-C-S, ×1.2 hot) is:", options: { A: "0.85 Ω", B: "0.95 Ω", C: "1.05 Ω", D: "1.20 Ω" }, answer: "B", explanation: "Hot (R1+R2) = 0.5 × 1.2 = 0.6 Ω. Hot Zs = Ze + hot (R1+R2) = 0.35 + 0.60 = 0.95 Ω. Compare with B32 max Zs of ~1.44 Ω at U₀ — well within limit." },
            { number: 2, prompt: "An installation's measured insulation resistance between L+N and earth is 0.7 MΩ. Compared with the BS 7671 minimum of 1 MΩ for 500 V test on circuits ≤ 500 V, this result is:", options: { A: "Acceptable", B: "Below the limit and requires investigation", C: "Acceptable provided 230 V tests are also done", D: "Acceptable provided RCD operates" }, answer: "B", explanation: "0.7 MΩ is below the 1 MΩ minimum from BS 7671 Section 643 / Table 64. Action: investigate which circuit is bringing the value down (split-circuit testing), look for water ingress, damaged insulation, or accumulated leakage from electronic equipment." },
            { number: 3, prompt: "A balanced three-phase 415 V (now 400 V nominal) star load draws 18 A line current at 0.9 PF. Apparent power and true power are approximately:", options: { A: "S = 12.5 kVA, P = 11.2 kW", B: "S = 7.47 kVA, P = 6.7 kW", C: "S = 18 kVA, P = 16.2 kW", D: "S = 25 kVA, P = 22.5 kW" }, answer: "A", explanation: "S = √3 × V_L × I_L = 1.732 × 400 × 18 = 12470 VA ≈ 12.5 kVA. P = S × cos φ = 12.5 × 0.9 = 11.2 kW. The same calculation applies to star and delta because V_L and I_L appear in the line-side formula." },
            { number: 4, prompt: "A 230 V cooker on a 32 A B-type MCB has a measured Zs of 0.94 Ω. The expected fault current is:", options: { A: "159 A", B: "245 A", C: "489 A", D: "1000 A" }, answer: "B", explanation: "I_F = U₀ / Zs = 230 / 0.94 = 244.7 A ≈ 245 A. Type B 32 A magnetic threshold = 5 × 32 = 160 A; at 245 A the MCB is in instantaneous magnetic operation, well within the 0.4 s requirement." },
            { number: 5, prompt: "Replacing a Type B 32 A MCB with a Type C 32 A MCB on the same circuit has the consequence:", options: { A: "Lower magnetic threshold (faster trip)", B: "Higher magnetic threshold (5–10 In) — Zs limit drops, requiring lower R1+R2 or larger CSA", C: "No change in Zs requirements", D: "Improved RCD performance" }, answer: "B", explanation: "Type C: 5–10 × In magnetic = 160–320 A for In = 32 A. The maximum Zs is taken at the upper bound: 230/320 = 0.72 Ω (vs ~1.44 Ω for Type B). Many existing circuits would fail if simply re-graded from B to C without redesign." },
            { number: 6, prompt: "A circuit's design current is 27 A. The chosen overcurrent protective device must satisfy I_b ≤ I_n ≤ I_z. The smallest standard MCB rating to use is:", options: { A: "20 A", B: "25 A", C: "32 A", D: "40 A" }, answer: "C", explanation: "Standard ratings: 6, 10, 16, 20, 25, 32, 40, 50, 63 A. The smallest one ≥ 27 A is 32 A. Once I_n is selected, the cable must have CCC ≥ 32 A after applying correction factors (Method, grouping, ambient, etc.)." },
            { number: 7, prompt: "A balanced three-phase 400 V supply feeds three identical 8 kW resistive heaters in star. The current per heater is:", options: { A: "20 A", B: "34.6 A", C: "60 A", D: "120 A" }, answer: "B", explanation: "In star, V_ph = V_L/√3 = 230 V. Each heater dissipates 8 kW at 230 V → I_ph = P/V = 8000/230 = 34.78 ≈ 34.6 A. In star, I_L = I_ph, so the line current is also 34.6 A. Equivalently P_total = 24 kW, I_L = 24000/(√3×400) ≈ 34.6 A." },
            { number: 8, prompt: "An 'L1' phase conductor in modern UK wiring is colour-coded:", options: { A: "Red", B: "Blue", C: "Brown (single-phase) / Brown (three-phase L1)", D: "Black" }, answer: "C", explanation: "Modern UK harmonised colours: single-phase L = brown, N = blue. Three-phase: L1 = brown, L2 = black, L3 = grey, N = blue. CPC: green/yellow throughout. Old red/yellow/blue or red/black still seen in pre-2006 installations." }
          ]
        },
        {
          id: "v5",
          questions: [
            { number: 1, prompt: "A 230 V single-phase load is fed by 1.5 mm² T+E (mV/A/m ≈ 29) over 35 m and draws 6 A. Voltage drop is:", options: { A: "3.05 V", B: "6.09 V", C: "9.14 V", D: "12.19 V" }, answer: "B", explanation: "V_drop = (29 × 6 × 35)/1000 = 6090/1000 = 6.09 V (~2.65% of 230 V). Just over the 3% lighting limit when on a lighting circuit, comfortable for general fixed equipment." },
            { number: 2, prompt: "A 12 kW three-phase 400 V cooker draws how much line current at unity PF?", options: { A: "10 A", B: "17.3 A", C: "30 A", D: "52 A" }, answer: "B", explanation: "P = √3 × V_L × I_L (cos φ = 1). I_L = 12000 / (1.732 × 400) = 12000 / 692.8 ≈ 17.32 A. The 30 A figure ignores √3 (uses 12000/400)." },
            { number: 3, prompt: "On a TN-S installation Ze = 0.6 Ω. Adding (R1+R2) = 0.84 Ω hot, the Zs is and the maximum permitted Zs for a 32 A B-type MCB at 230 V is:", options: { A: "Zs = 1.44 Ω, max permitted = 1.44 Ω — at the limit", B: "Zs = 1.44 Ω, max permitted = 0.96 Ω — non-compliant", C: "Zs = 0.84 Ω, max permitted = 1.44 Ω — compliant", D: "Zs = 1.84 Ω, max permitted = 1.44 Ω — non-compliant" }, answer: "A", explanation: "Hot Zs = 0.6 + 0.84 = 1.44 Ω. Max permitted Zs for a B-type 32 A is U₀ / I_a = 230 / (5 × 32) = 230/160 = 1.44 Ω. Sitting at the limit means any deterioration would push the circuit out of compliance — designers usually leave headroom." },
            { number: 4, prompt: "A 6 A Type C MCB feeds a small motor circuit in 1.5 mm² T+E. The cable is grouped (Cg = 0.7) and run in 30 °C ambient (Ca = 1.0). The 1.5 mm² Method C tabulated CCC ≈ 19.5 A. Effective CCC is:", options: { A: "9.75 A", B: "13.65 A", C: "19.5 A", D: "27 A" }, answer: "B", explanation: "Effective CCC = 19.5 × 0.7 × 1.0 = 13.65 A. Comfortably above the 6 A protective device rating, so the cable size is acceptable. Voltage drop and short-circuit checks would still need to be done." },
            { number: 5, prompt: "An EICR records insulation resistance of 0.4 MΩ on a 230 V lighting circuit. Action required is:", options: { A: "None — value is acceptable", B: "Investigate and rectify — below the 1 MΩ minimum", C: "Test at 1000 V instead", D: "Replace the consumer unit" }, answer: "B", explanation: "BS 7671 Section 643 / Table 64: minimum 1 MΩ for circuits ≤ 500 V. 0.4 MΩ indicates degraded insulation — possible water ingress, damaged conductors, or accumulated leakage from connected equipment. Investigate and rectify before recommissioning." },
            { number: 6, prompt: "A balanced three-phase induction motor takes 18 A line current at 400 V, 0.85 PF, with measured input power 10.6 kW. The apparent power is:", options: { A: "9 kVA", B: "10.6 kVA", C: "12.5 kVA", D: "13.9 kVA" }, answer: "C", explanation: "S = P / cos φ = 10.6 / 0.85 = 12.47 kVA ≈ 12.5 kVA. Cross-check: S = √3 × V_L × I_L = 1.732 × 400 × 18 = 12470 VA — same result." },
            { number: 7, prompt: "Why does a long voltage-drop margin matter even when the circuit's overcurrent protection is properly sized?", options: { A: "Lower voltage at the load reduces output (e.g. lower heater power, motor torque, dimmer lamps) and may push current up to compensate", B: "It only affects the supply company's revenue", C: "Voltage drop never matters once protection is set", D: "It only matters at full load" }, answer: "A", explanation: "Voltage drop reduces the working voltage at the load. P ∝ V² for fixed-resistance loads, so a 5% voltage drop causes ~10% power loss in heating. Motors compensate by drawing more current, raising losses further. Voltage drop limits in BS 7671 are therefore both safety and performance based." },
            { number: 8, prompt: "An EV charge point installed on a TN-C-S supply uses an 'open-PEN' protection device. This device monitors:", options: { A: "Earth fault current via residual-current detection", B: "Voltage between the supply neutral and a reference earth, disconnecting the EV circuit if a PEN open-circuit is detected", C: "Frequency", D: "Power factor" }, answer: "B", explanation: "Open-PEN protection measures the supply N voltage relative to a reference (typically a small earth electrode or via the local PEN voltage), disconnecting the load if the N-PEN voltage rises significantly — symptomatic of a broken PEN. This avoids the chassis-rise hazard on EV charging without needing a separate TT earth." }
          ]
        }
      ]
    }
  ],
  scoring: [
    { threshold: 0.9, label: "Strong — solid grasp of principles, ready for the regulation-focused exams" },
    { threshold: 0.7, label: "Solid — minor gaps in calculations or AC theory" },
    { threshold: 0.5, label: "Needs targeted revision — re-read the on-site guide and Hughes Electrical Technology" },
    { threshold: 0, label: "Major gaps — return to fundamentals before retrying" }
  ],
  priorities: [
    "Ohm's law and power triangle: V=IR, P=VI, P=I²R, P=V²/R. Be able to rearrange and combine.",
    "AC theory essentials: peak vs RMS (V_peak = √2 × V_rms), power factor (true/apparent/reactive), single-phase vs three-phase relationships (V_L = √3 × V_ph).",
    "Cable selection chain: design current → CCC after correction factors (Method, grouping, ambient, thermal insulation) → voltage drop (mV/A/m × I × L) → fault-current rating.",
    "Earthing systems: TT, TN-S, TN-C-S/PME, IT — be able to draw the fault-current path for each.",
    "Protective devices: fuse vs MCB vs RCBO vs RCD; characteristic curves (Type B/C/D); discrimination/selectivity; the three roles (overload, fault, additional protection)."
  ]
};
