/**
 * Independently authored calculator examples.
 *
 * These values are a reviewable contract, not snapshots generated by
 * `calculators.ts`. Keep the arithmetic in each `basis` note checkable by hand
 * and update a golden value only after independently re-verifying the formula.
 *
 * Containment convention: a bend-cut mark uses
 *   tan((total bend / cuts) / 2) * containment width.
 * The removed "containment bend start" calculator is intentionally absent.
 */

export const CALCULATOR_GOLDEN_FIXTURES = {
  "containment-rod": [
    {
      id: "default-site-drop",
      basis: "3165 - 2900 = 265; rod adds 100; underside adds 40.",
      args: ["3165", "2900", "100", "40"],
      expected: {
        validationMessage: null,
        actualDropValue: "265 mm",
        rodCutLengthValue: "365 mm",
        bottomOfUnistrutDropValue: "305 mm",
      },
    },
    {
      id: "zero-drop-remains-valid",
      basis: "Equal overall and top heights give zero drop; allowances remain physical lengths.",
      args: ["2400", "2400", "75", "41"],
      expected: {
        validationMessage: null,
        actualDropValue: "0 mm",
        rodCutLengthValue: "75 mm",
        bottomOfUnistrutDropValue: "41 mm",
      },
    },
    {
      id: "top-cannot-exceed-overall-height",
      basis: "A 2500 mm top reference cannot fit within a 2400 mm overall height.",
      args: ["2400", "2500", "75", "41"],
      expected: {
        validationMessage: "Height to top of Unistrut cannot be more than overall height.",
        actualDropValue: "-- mm",
        rodCutLengthValue: "-- mm",
        bottomOfUnistrutDropValue: "-- mm",
      },
    },
  ],

  "unistrut-length": [
    {
      id: "three-containment-layout",
      basis: "Widths 225 + 125 + 100, side allowances 50 + 50, and two 50 mm gaps total 650.",
      containments: [
        { id: 1, label: "Tray", width: "225" },
        { id: 2, label: "Basket", width: "125" },
        { id: 3, label: "Trunking", width: "100" },
      ],
      allowances: ["50", "50", "50"],
      expected: {
        validationMessage: null,
        totalContainmentWidthValue: "450 mm",
        totalSideAllowanceValue: "100 mm",
        totalGapAllowanceValue: "100 mm",
        exactLengthValue: "650 mm",
        finalLengthValue: "650 mm",
        gapLabel: "2 gaps",
      },
    },
    {
      id: "stock-rounds-up-not-nearest",
      basis: "230 + 50 + 50 = 330, which rounds upward to the next 50 mm stock length: 350.",
      containments: [{ id: 1, label: "Tray", width: "230" }],
      allowances: ["50", "50", "50"],
      expected: {
        validationMessage: null,
        totalContainmentWidthValue: "230 mm",
        totalSideAllowanceValue: "100 mm",
        totalGapAllowanceValue: "0 mm",
        exactLengthValue: "330 mm",
        finalLengthValue: "350 mm",
        gapLabel: "0 gaps",
      },
    },
    {
      id: "negative-gap-is-invalid",
      basis: "Physical widths, gaps and side allowances cannot be negative.",
      containments: [{ id: 1, label: "Tray", width: "225" }],
      allowances: ["50", "50", "-1"],
      expected: {
        validationMessage: "Widths, allowances, and gaps cannot be negative.",
        totalContainmentWidthValue: "-- mm",
        totalSideAllowanceValue: "-- mm",
        totalGapAllowanceValue: "-- mm",
        exactLengthValue: "-- mm",
        finalLengthValue: "-- mm",
        gapLabel: "0 gaps",
      },
    },
    {
      id: "zero-width-row-is-invalid",
      basis: "A containment row needs a positive physical width; zero cannot contribute a real support span.",
      containments: [{ id: 1, label: "Tray", width: "0" }],
      allowances: ["50", "50", "50"],
      expected: {
        validationMessage: "Containment widths must be greater than 0 mm.",
        totalContainmentWidthValue: "-- mm",
        totalSideAllowanceValue: "-- mm",
        totalGapAllowanceValue: "-- mm",
        exactLengthValue: "-- mm",
        finalLengthValue: "-- mm",
        gapLabel: "0 gaps",
      },
    },
  ],

  "angle-drop": [
    {
      id: "forty-five-degree-right-triangle",
      basis: "10 / sin(45 degrees) = 14.1421; its horizontal projection is 10.",
      args: ["10", "45", "0", "0", "0", "cm", false, false, "0"],
      expected: {
        angledLengthValue: "14.14 cm",
        offsetValue: "10 cm",
        totalLengthValue: "14.14 cm",
      },
    },
    {
      id: "angle-is-measured-from-horizontal",
      basis: "12 / sin(30 degrees) = 24; 24 cos(30 degrees) = 20.7846; straights plus allowance add 13.",
      args: ["12", "30", "5", "7", "1", "mm", false, false, "0"],
      expected: {
        angledLengthValue: "24 mm",
        offsetValue: "20.78 mm",
        totalLengthValue: "37 mm",
      },
    },
    {
      id: "two-prefabricated-bends-reduce-the-rise",
      basis: "A 20 cm rise less two 5 cm bend heights leaves 10 cm; 10 / sin(45 degrees) = 14.1421.",
      args: ["20", "45", "0", "0", "0", "cm", true, true, "5"],
      expected: {
        angledLengthValue: "14.14 cm",
        offsetValue: "10 cm",
        totalLengthValue: "14.14 cm",
      },
    },
    {
      id: "ninety-degrees-is-outside-this-calculator",
      basis: "The developed-angle tool accepts an acute angle only; a square change is not this construction.",
      args: ["10", "90", "0", "0", "0", "cm", false, false, "0"],
      expected: {
        angledLengthValue: "--",
        offsetValue: "--",
        totalLengthValue: "--",
      },
    },
    {
      id: "selected-bend-needs-positive-height",
      basis: "A selected prefabricated bend cannot be deducted from the rise when its entered height is negative.",
      args: ["20", "45", "0", "0", "0", "cm", true, false, "-5"],
      expected: {
        angledLengthValue: "--",
        offsetValue: "--",
        totalLengthValue: "--",
      },
    },
    {
      id: "selected-bend-needs-entered-height",
      basis: "A selected prefabricated bend needs an explicit finite positive height before its deduction is valid.",
      args: ["20", "45", "0", "0", "0", "cm", true, false, ""],
      expected: {
        angledLengthValue: "--",
        offsetValue: "--",
        totalLengthValue: "--",
      },
    },
  ],

  "trunking-opposite-mark": [
    {
      id: "forty-five-degree-half-angle-convention",
      basis: "tan(45 / 2 degrees) * 100 = 41.4214 mm; show 41.4 and fabricate at 41 mm.",
      args: ["45", "100"],
      expected: {
        validationMessage: null,
        desiredAngleValue: "45 deg",
        calculationAngleValue: "22.5 deg",
        adjacentValue: "100 mm",
        oppositeValue: "41.4 mm",
        roundedOppositeValue: "41 mm",
      },
    },
    {
      id: "sixty-degree-non-default-width",
      basis: "tan(30 degrees) * 150 = 86.6025 mm; show 86.6 and fabricate at 87 mm.",
      args: ["60", "150"],
      expected: {
        validationMessage: null,
        desiredAngleValue: "60 deg",
        calculationAngleValue: "30 deg",
        adjacentValue: "150 mm",
        oppositeValue: "86.6 mm",
        roundedOppositeValue: "87 mm",
      },
    },
    {
      id: "straight-angle-is-not-a-fabricated-bend",
      basis: "The half-angle tangent construction is finite only for a total angle strictly below 180 degrees.",
      args: ["180", "100"],
      expected: {
        validationMessage: "Desired bend angle must be greater than 0 and less than 180 degrees.",
        desiredAngleValue: "-- deg",
        calculationAngleValue: "-- deg",
        adjacentValue: "-- mm",
        oppositeValue: "-- mm",
        roundedOppositeValue: "-- mm",
      },
    },
  ],

  "tray-bend-cut": [
    {
      id: "single-cut-ninety-degree-convention",
      basis: "One cut carries the full 90 degree turn; tan(45 degrees) * 100 = 100 mm.",
      args: ["90", "1", "100"],
      expected: {
        validationMessage: null,
        bendAngleValue: "90 deg",
        totalBendValue: "90 deg",
        bendPerCutValue: "90 deg",
        calculationAngleValue: "45 deg",
        trayWidthValue: "100 mm",
        setbackValue: "100 mm",
        roundedSetbackValue: "100 mm",
        cutsLabel: "1 cut",
      },
    },
    {
      id: "two-cuts-split-the-total-bend",
      basis: "90 / 2 = 45 degrees per cut; tan(22.5 degrees) * 100 = 41.4214 mm per mark.",
      args: ["90", "2", "100"],
      expected: {
        validationMessage: null,
        bendAngleValue: "90 deg",
        totalBendValue: "90 deg",
        bendPerCutValue: "45 deg",
        calculationAngleValue: "22.5 deg",
        trayWidthValue: "100 mm",
        setbackValue: "41.4 mm",
        roundedSetbackValue: "41 mm",
        cutsLabel: "2 cuts",
      },
    },
    {
      id: "three-cut-wide-containment",
      basis: "120 / 3 = 40 degrees per cut; tan(20 degrees) * 150 = 54.5955 mm.",
      args: ["120", "3", "150"],
      expected: {
        validationMessage: null,
        bendAngleValue: "120 deg",
        totalBendValue: "120 deg",
        bendPerCutValue: "40 deg",
        calculationAngleValue: "20 deg",
        trayWidthValue: "150 mm",
        setbackValue: "54.6 mm",
        roundedSetbackValue: "55 mm",
        cutsLabel: "3 cuts",
      },
    },
    {
      id: "fractional-cut-count-is-invalid",
      basis: "A fabricated notch count is a positive whole number.",
      args: ["90", "2.5", "100"],
      expected: {
        validationMessage: "Number of cuts must be a whole number of 1 or more.",
        bendAngleValue: "-- deg",
        totalBendValue: "-- deg",
        bendPerCutValue: "-- deg",
        calculationAngleValue: "-- deg",
        trayWidthValue: "-- mm",
        setbackValue: "-- mm",
        roundedSetbackValue: "-- mm",
        cutsLabel: "-- cuts",
      },
    },
  ],

  power: [
    {
      id: "single-phase-active-power",
      basis: "230 V * 10 A * 1.0 / 1000 = 2.3 kW.",
      args: ["power", "single", "10", "230", "1"],
      expected: { label: "Power", resultValue: "2.3 kW" },
    },
    {
      id: "balanced-three-phase-active-power",
      basis: "sqrt(3) * 400 V * 25 A * 0.8 / 1000 = 13.8564 kW.",
      args: ["power", "three", "25", "400", "0.8"],
      expected: { label: "Power", resultValue: "13.86 kW" },
    },
    {
      id: "three-phase-current-from-power",
      basis: "10000 W / (sqrt(3) * 400 V * 0.95) = 15.193 A.",
      args: ["current", "three", "10", "400", "0.95"],
      expected: { label: "Current", resultValue: "15.19 A" },
    },
    {
      id: "voltage-from-single-phase-power",
      basis: "4600 W / (20 A * 1.0) = 230 V.",
      args: ["voltage", "single", "4.6", "20", "1"],
      expected: { label: "Voltage", resultValue: "230 V" },
    },
    {
      id: "power-factor-cannot-exceed-one",
      basis: "The calculator accepts a power factor in the interval (0, 1].",
      args: ["current", "single", "1", "230", "1.01"],
      expected: { label: "Current", resultValue: "-- A" },
    },
  ],

  "voltage-drop": [
    {
      id: "single-phase-two-conductor-path",
      basis: "2 * 20 A * 20 m * 0.022 / 2.5 = 7.04 V; 7.04 / 230 = 3.0609 percent.",
      args: ["single", "20", "20", "2.5", "230"],
      expected: {
        dropValue: "7.04 V",
        percentValue: "3.06 %",
        mvPerAmpMeterValue: "17.6",
      },
    },
    {
      id: "balanced-three-phase-path",
      basis: "sqrt(3) * 20 A * 20 m * 0.022 / 2.5 = 6.0968 V; 6.0968 / 400 = 1.5242 percent.",
      args: ["three", "20", "20", "2.5", "400"],
      expected: {
        dropValue: "6.1 V",
        percentValue: "1.52 %",
        mvPerAmpMeterValue: "15.24",
      },
    },
    {
      id: "one-square-millimetre-copper-coefficient",
      basis: "The 70 C model gives 2 * 0.022 / 1 * 1000 = 44 mV/A/m.",
      args: ["single", "10", "10", "1", "230"],
      expected: {
        dropValue: "4.4 V",
        percentValue: "1.91 %",
        mvPerAmpMeterValue: "44",
      },
    },
    {
      id: "zero-conductor-area-is-invalid",
      basis: "A zero conductor cross-sectional area cannot define resistance or voltage drop.",
      args: ["single", "20", "20", "0", "230"],
      expected: {
        dropValue: "-- V",
        percentValue: "-- %",
        mvPerAmpMeterValue: "--",
      },
    },
  ],

  "breaker-sizing": [
    {
      id: "next-standard-rating",
      basis: "18 A is above 16 A, so the next rating in the app list is 20 A.",
      args: ["current", "18", "", "single", "230", "0.95"],
      expected: {
        breakerValue: "20 A",
        currentValue: "18 A",
        rangeValue: "Over 16 A to 20 A",
      },
    },
    {
      id: "exact-lowest-rating",
      basis: "A 6 A design current exactly matches the first standard rating.",
      args: ["current", "6", "", "single", "230", "1"],
      expected: {
        breakerValue: "6 A",
        currentValue: "6 A",
        rangeValue: "Up to 6 A",
      },
    },
    {
      id: "single-phase-power-input",
      basis: "4000 W / (230 V * 1.0) = 17.3913 A, requiring the 20 A list entry.",
      args: ["power", "", "4", "single", "230", "1"],
      expected: {
        breakerValue: "20 A",
        currentValue: "17.39 A",
        rangeValue: "Over 16 A to 20 A",
      },
    },
    {
      id: "upper-listed-rating-boundary",
      basis: "A 100 A design current exactly matches the largest rating in the app list.",
      args: ["current", "100", "", "single", "230", "1"],
      expected: {
        breakerValue: "100 A",
        currentValue: "100 A",
        rangeValue: "Over 80 A to 100 A",
      },
    },
    {
      id: "above-listed-range-has-no-selected-breaker",
      basis: "A 150 A design current exceeds the 100 A list maximum, so no listed breaker is a safe selection.",
      args: ["current", "150", "", "single", "230", "1"],
      expected: {
        breakerValue: "-- A",
        currentValue: "150 A",
        rangeValue: "Over 100 A — no listed size",
      },
    },
    {
      id: "invalid-power-factor-does-not-size",
      basis: "A power-mode calculation needs a power factor in the interval (0, 1].",
      args: ["power", "", "4", "single", "230", "0"],
      expected: {
        breakerValue: "-- A",
        currentValue: "-- A",
        rangeValue: "--",
      },
    },
  ],

  "conduit-fill": [
    {
      id: "three-six-millimetre-cables",
      basis: "3 * (6 / 20)^2 * 100 = 27 percent; circular areas are 84.823 used and 229.336 remaining.",
      args: ["20", "6", "3", "40"],
      expected: {
        fillValue: "27 %",
        usedAreaValue: "84.82 mm²",
        remainingValue: "229.3 mm²",
        overFill: false,
      },
    },
    {
      id: "exactly-at-fill-limit",
      basis: "10 * (4 / 20)^2 * 100 = exactly 40 percent, so a 40 percent limit is not exceeded.",
      args: ["20", "4", "10", "40"],
      expected: {
        fillValue: "40 %",
        usedAreaValue: "125.7 mm²",
        remainingValue: "188.5 mm²",
        overFill: false,
      },
    },
    {
      id: "fill-limit-exceeded",
      basis: "6 * (6 / 20)^2 * 100 = 54 percent, which exceeds a 40 percent limit.",
      args: ["20", "6", "6", "40"],
      expected: {
        fillValue: "54 %",
        usedAreaValue: "169.6 mm²",
        remainingValue: "144.5 mm²",
        overFill: true,
      },
    },
    {
      id: "cable-count-must-be-whole",
      basis: "A physical cable count cannot be fractional.",
      args: ["20", "6", "2.5", "40"],
      expected: {
        fillValue: "-- %",
        usedAreaValue: "-- mm²",
        remainingValue: "-- mm²",
        overFill: false,
      },
    },
  ],

  "structural-limits": [
    {
      id: "one-hundred-millimetre-wall-and-two-hundred-millimetre-joist",
      basis: "100 / 3 = 33.333; 100 / 6 = 16.667; 200 * 0.125 = 25.",
      args: ["100", "200"],
      expected: {
        vertical: "33.33 mm",
        horizontal: "16.67 mm",
        notch: "25 mm",
      },
    },
    {
      id: "block-and-joist-non-integer-results",
      basis: "140 / 3 = 46.667; 140 / 6 = 23.333; 220 * 0.125 = 27.5.",
      args: ["140", "220"],
      expected: {
        vertical: "46.67 mm",
        horizontal: "23.33 mm",
        notch: "27.5 mm",
      },
    },
    {
      id: "non-positive-dimensions-are-invalid",
      basis: "Structural dimensions must be positive physical lengths.",
      args: ["0", "0"],
      expected: {
        vertical: "-- mm",
        horizontal: "-- mm",
        notch: "-- mm",
      },
    },
  ],
} as const;

export type GoldenCalculatorID = keyof typeof CALCULATOR_GOLDEN_FIXTURES;
